Enforce Return
slimphp/Slim pull request #2015
Opened 2016-10-12 18:55 UTC by geggleto

- Adds a new option to enforce return's from route actions

2016-10-12 18:58 UTC, dopesong commented on Slim/Exception/BadRouteReturnException.php
> +/**
Copyright?

2016-10-12 19:17 UTC, akrabat requested changes
Looking good. Some minor bits and bobs noted.

2016-10-12 19:17 UTC, akrabat commented on Slim/Route.php
> +        $this->enforceReturn = $enforceReturn;
Cast to a `bool` please.

2016-10-12 19:17 UTC, akrabat commented on Slim/Route.php
> +use FastRoute\BadRouteException;
Not needed.

2016-10-12 19:17 UTC, akrabat commented on Slim/Route.php
> +     * @var bool
Needs title.

2016-10-12 19:17 UTC, akrabat commented on Slim/Route.php
> +
Too many blank lines here.

2016-10-12 19:17 UTC, akrabat commented on Slim/Route.php
> +    protected $enforceReturn = false;
Rename to `enforceReturnOfResponse` ?

2016-10-12 19:17 UTC, akrabat commented on tests/RouteTest.php
> +        $route->setOutputBuffering(false);
Can we have a second test where this is the default please?

2016-10-12 19:44 UTC, akrabat commented on tests/RouteTest.php
> +        $route->setOutputBuffering(true);
`true` is not a valid setting for outputBuffering.

2016-10-12 19:53 UTC, dopesong commented on Slim/App.php
> +
Double empty line?

2016-11-18 14:11 UTC, akrabat commented
I've thought so more about this and while I appreciate that I asked for this, I now think it'd be better to wait for 4 and handle it better there.

2016-11-21 15:22 UTC, geggleto commented
@akrabat do you want to leave the PR open or should be close it?

2016-11-26 15:18 UTC, closed without merging