[WIP] Feature output buffer middleware
slimphp/Slim pull request #2166
Opened 2017-03-08 14:18 UTC by codeguy

Work in progress. Opening PR for feedback.

2017-03-08 14:21 UTC, codeguy commented
Changes so far include:

1. Require all route callbacks to return PSR7 response.
2. Remove all output buffering concerns from `App` and ``Route` classes.

2017-03-08 19:37 UTC, akrabat requested changes
* ~Need tests for the new `OutputBuffering` middleware~
* Can you add a CHANGELOG entry please?

Update - I can't read!

2017-03-08 19:50 UTC, akrabat requested changes

2017-03-08 19:50 UTC, akrabat commented on tests/RouteTest.php
>      public function testInvokeWhenReturningAString()
I think this test should return a string and expect an Exception to happen?

2017-03-09 03:36 UTC, geggleto requested changes

2017-03-09 03:36 UTC, geggleto commented on Slim/App.php
> -        }
I honestly think that we can remove it.

Dump and Die will still work, which is I feel what a majority of people do anyway.

2017-03-09 03:36 UTC, geggleto commented on tests/RouteTest.php
>      public function testInvokeWhenReturningAString()
@akrabat I think the name of the test should change. This test should be renamed.

`testEchoingOutputIsEmpty`

`testReturningStringThrowsException` ?

2017-06-09 21:53 UTC, copynpaste commented on Slim/Middleware/OutputBuffering.php
> +        } catch (\Throwable $e) {
PHP 5 vs PHP 7 #2175

2017-06-27 06:53 UTC, merged