Pass app into group callable
slimphp/Slim pull request #2229
Opened 2017-05-17 15:32 UTC by geekish

As discussed in #1976, route group callables are bound to App, making the use of closures easy, but App is not passed to groups on invoke so an invokable class will not work.

I chose to remove the closure binding altogether as passing App through on invoke negates the need to do this anymore. The tests weren't even using the feature...

2017-05-17 17:43 UTC, silentworks commented
I am happy with this change getting added into Slim 4, @geekish has also provided example code to show the use of this feature, which current implementation doesn't allow.

https://gist.github.com/geekish/3a1cf866aec0a6ee1935007cbf915d78

2017-05-18 00:04 UTC, geggleto commented
I need to think about it more. The idea of passing App around strikes me as a code smell.

I understand the desire to fix the problem with route groups, and registering routes and what not.

I think it would make more sense to only pass through the Router object.

//cc @akrabat

2017-05-23 10:34 UTC, silentworks commented
@geggleto we can't pass the `Router` instead, because the `Router` doesn't carry these methods, these are helper methods [get, post, put, delete, map] that are created inside of `App`.

2017-05-23 13:11 UTC, geggleto commented
@silentworks maybe they should be on the router and not the app ;)

2017-05-25 00:28 UTC, geekish commented
I would definitely prefer that we pass Router through instead and get rid of the helper methods on App, but that would be out of the scope for this PR.

Besides that, I don't see how passing App through is any smellier than binding the closure to it; that kind of magic seems pretty smelly to me.

2017-05-25 11:09 UTC, silentworks approved these changes

2017-05-25 19:31 UTC, sharifzadesina commented
I don't like this PR, there is no reason to add `App` to the route group, routing and application are separate packages.

2017-05-25 19:32 UTC, silentworks commented
@sharifzadesina we are already doing this in the form of closure binding. So I am not sure why there is fuss about this PR.

2017-05-25 19:37 UTC, sharifzadesina commented
@silentworks of course you are, and I know this will sequent injection of the `App` class, but this is not good design, imagine router without `App` class, what will happen? your router will be useless.

2017-05-25 19:38 UTC, silentworks commented
@sharifzadesina so the point you are making has nothing to do with this PR. Someone else should send another PR to fix the issue you are concerned about.

2017-05-25 19:40 UTC, sharifzadesina commented
@silentworks Maybe, but by this PR you are making the bad design bigger and bigger. anyway this is just my idea.

2017-05-25 19:42 UTC, silentworks commented
@sharifzadesina no we aren't making it bigger, it still the same magnitude as it was before this PR. This PR however is making the use more consistent.

2017-05-25 19:53 UTC, silentworks commented
For past commenters and future commenters on this issue, I want to make it clear that coming with an argument about design decision has no effect on this PR, this PR was created after the design decision was taken, this PR is just making it more clear as to how you create routes in route groups.

I find it distasteful that many have commented about bad design on a PR by a first time contributor that has/had no effect on the bad design decision that was taken more than a year ago. If you wish to fix this bad design decision, raise a new issue or send a PR, please don't make this PR out to be what its not.

2017-05-25 20:11 UTC, geggleto approved these changes

2017-05-25 20:12 UTC, geggleto commented
@geekish I think we should revisit the groups in a different way. :)

2017-05-26 09:56 UTC, akrabat commented
One side effect of removing the binding is that it will be that much harder to upgrade from 3 to 4. Is the fact that you don't like the closure binding feature of PHP a reason to remove it?

2017-05-27 09:18 UTC, silentworks commented
I think its more of consistency and my IDE would know how to give me autocomplete hint based on `$app` than currently where I get none based on `$this`.

2017-06-27 18:31 UTC, akrabat commented
I'm happy to pass in `$app` to the closure / `__invoke()`, I'm just questioning whether we should remove the binding of `$app` to  `$this` for closures. 

I think that smoothing out upgraders from 3 warrants it.

2017-06-29 11:17 UTC, akrabat requested changes
Please reinstate binding `$app` to `$this`, but add a `trigger_error` in the `if` statement of type `E_USER_DEPRECATED` noting that the binding of $this to the group is deprecated.

2017-08-17 15:30 UTC, akrabat commented
Note that we could also do this for `3.x` to provide a forward migration path.

2017-08-19 14:10 UTC, geekish commented
I've re-added the closure binding, but didn't add a `trigger_error` - I agree there needs to be some way to notify the user about the deprecation but that would trigger on every route using a closure whether the user utilizes the bind or not.

2017-08-21 12:58 UTC, geggleto commented
thank you @geekish  :)

2017-09-21 08:10 UTC, akrabat approved these changes

2017-09-21 09:38 UTC, akrabat commented
Any reason we can't do this for Slim 3 too?

2017-09-21 09:39 UTC, merged