Refactor router class
slimphp/Slim pull request #2239
Opened 2017-06-06 16:32 UTC by ipabz

2017-06-06 16:38 UTC, geggleto requested changes

2017-06-06 16:38 UTC, geggleto commented on Slim/Router.php
> +        $routes = array_filter($this->routes, function ($route) use ($name) {
This should only ever return one route.

2017-06-06 16:38 UTC, geggleto commented on Slim/Router.php
> +        $routes = array_filter($this->routes, function ($route) use ($name) {
This is also not an improvement on readability in my opinion.

2017-06-07 07:06 UTC, copynpaste commented on Slim/Router.php
> +            return $this->dispatcher;
Why do you want multiple return statements?

2017-06-07 07:06 UTC, copynpaste commented on Slim/Router.php
> +            if ($name === $route->getName()) {
Could be a potential BC break?

2017-06-07 11:44 UTC, silentworks commented on Slim/Router.php
> +            return $this->dispatcher;
I think its the idea of return early, I am however not sure how much of a speed improvement this gives.

2017-06-07 13:11 UTC, copynpaste commented on Slim/Router.php
> +            return $this->dispatcher;
Should be nearly nothing as there is no code between the if and return.

2017-06-07 20:10 UTC, geggleto commented on Slim/Router.php
> +            if ($name === $route->getName()) {
Yes, it would.

2017-06-08 09:48 UTC, silentworks commented
As I don't think there are any benefits to these changes, I will be rejecting this PR.

2017-06-08 09:48 UTC, closed without merging