Adding plain not found response for OPTIONS requests
slimphp/Slim pull request #2244
Opened 2017-06-14 12:00 UTC by piotr-cz

OPTIONS requests are being sent by browsers with the `Accept: */*` header (as opposed to this [MDN article](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS)).

This is causing AbstractHandler::determineContentType method to evaluate response format as `text/html` and so NotFound handler creates a HTML response  (for example I'm rendering a 4Kb html page with stylesheets and suff) which is not necessary for a preflight request.

So I've added a check similar to the [one in NotAllowed handler](https://github.com/slimphp/Slim/blob/3.8.1/Slim/Handlers/NotAllowed.php#L36-L39) and corresponding `renderPlainNotFoundOutput` method. NotFound response body for OPTIONS requests is now `Not found`.

This is very similar to https://github.com/slimphp/Slim/commit/a2cc9d9801c037f886b9253f936ef5f0994c5f1a when such behavior has been added to `NotAllowed` handler.

2017-06-14 12:49 UTC, piotr-cz commented
Travis failed on PHP:hhvm build:
```
HHVM is no longer supported on Ubuntu Precise. Please consider using Trusty with `dist: trusty`.
```

2017-06-15 09:47 UTC, Sam-Burns commented
@piotr-cz We're aware of the build problem.  It is addressed by https://github.com/slimphp/Slim/pull/2245.

2017-06-27 17:28 UTC, akrabat commented
@piotr-cz can you rebase and then we can check that travis passes

2017-06-29 11:33 UTC, akrabat requested changes
Please rebase for CI tests

2017-06-29 11:48 UTC, piotr-cz commented
I've rebased, see https://github.com/piotr-cz/Slim/commits/29d517cfb98df8a173088d1ed69b955bf2b29799/.travis.yml

No idea why it doesn't show up, just as a notice after https://github.com/slimphp/Slim/pull/2244#issuecomment-308683978

2017-06-29 12:36 UTC, akrabat requested changes
Needs a unit test too. Sorry that I didn't mention this earlier.

2017-07-03 07:37 UTC, piotr-cz commented
I need a hand here:
What is the proper way to create an OPTIONS mock request?
The `getRequest` method [may receive a method](https://github.com/slimphp/Slim/blob/3.8.1/tests/Handlers/NotFoundTest.php#L62), but it doesn't use it.

2017-08-13 09:21 UTC, merged

2017-08-13 09:21 UTC, akrabat commented
Thanks.