Replace addContentLengthHeader with ContentLength Middleware
slimphp/Slim pull request #2254
Opened 2017-06-29 10:16 UTC by akrabat

This feature isn't needed in core and is better as optional middleware.

2017-06-29 11:19 UTC, damianopetrungaro commented
@akrabat 
As discussed on Slack for the AppTest:



    public function testAddSettings()
    {
        $app = new App();
        $app->addSettings(['foo' => 'bar']);
        $this->assertAttributeContains('bar', 'settings', $app);
    }

    public function testAddSetting()
    {
        $app = new App();
        $app->addSetting('foo', 'bar');
        $this->assertAttributeContains('bar', 'settings', $app);
    }


with this it works 😄

2017-06-29 11:33 UTC, damianopetrungaro commented
Or even better:

    public function testAddSettings()
    {
        $app = new App();
        $reflection = new ReflectionProperty(App::class, 'settings');
        $reflection->setAccessible(true);
        $reflection->setValue($app, []);
        $app->addSettings(['foo' => 'bar']);
        $this->assertSame(['foo' => 'bar'], $reflection->getValue($app));
    }

    public function testAddSetting()
    {
        $app = new App();
        $reflection = new ReflectionProperty(App::class, 'settings');
        $reflection->setAccessible(true);
        $reflection->setValue($app, []);
        $app->addSetting('foo', 'bar');
        $this->assertSame(['foo' => 'bar'], $reflection->getValue($app));
    }

2017-08-13 09:48 UTC, akrabat commented
Ping @geggleto

2017-08-14 13:26 UTC, geggleto requested changes

2017-08-14 13:26 UTC, geggleto commented on Slim/Middleware/ContentLength.php
> +            $response = $response->withHeader('Content-Length', (string) $size);
.... why are we casting it to a string? ... my gut says that is a really bad idea.

2017-08-14 13:26 UTC, geggleto commented on tests/Middleware/ContentLengthTest.php
> +        $this->assertEquals(4, $newResponse->getHeaderLine('Content-Length'));
This test should also assert that the body's content is actually 'Body'

@akrabat what about multi-byte character sets?

2017-08-15 07:30 UTC, akrabat commented on Slim/Middleware/ContentLength.php
> +            $response = $response->withHeader('Content-Length', (string) $size);
[`withHeader()`](https://github.com/php-fig/http-message/blob/master/src/MessageInterface.php#L128) is defined as taking a string as the second parameter.

2017-08-15 07:44 UTC, akrabat commented on tests/Middleware/ContentLengthTest.php
> +        $this->assertEquals(4, $newResponse->getHeaderLine('Content-Length'));
Why? The code under test doesn't touch the body and ensuring the body is the correct text is covered by tests on `Response` and `App`.

2017-08-15 07:45 UTC, akrabat commented on tests/Middleware/ContentLengthTest.php
> +        $this->assertEquals(4, $newResponse->getHeaderLine('Content-Length'));
Size of multi-byte character sets is an issue for `Slim\Http\Stream()` and should be tested there I think?

2017-08-15 07:47 UTC, akrabat commented on tests/Middleware/ContentLengthTest.php
> +        $this->assertEquals(4, $newResponse->getHeaderLine('Content-Length'));
There's an argument that the test should be:

```php
$this->assertEquals($response->getBody()->getSize(), $newResponse->getHeaderLine('Content-Length'));
```

or even:

```php
$this->assertTrue($newResponse->hasHeader('Content-Length'));
```

2017-08-15 07:50 UTC, akrabat commented
Renamed to `ContentLengthMiddleware` as per https://github.com/slimphp/Slim/pull/2288#discussion_r133005546

2017-08-15 08:26 UTC, campersau commented on UPGRADING.md
> +* [2254] - You need to add the `Middleware\ContentLength` middleware if you want Slim to add this automatically.
`ContentLengthMiddleware`?
Maybe the `OutputBuffering` should also be renamed?

2017-08-15 08:39 UTC, akrabat commented on UPGRADING.md
> +* [2254] - You need to add the `Middleware\ContentLength` middleware if you want Slim to add this automatically.
Good catch. Thanks.

Yes, 'OutputBuffering' will need renaming too, but that's a separate PR if you fancy doing it?

2017-08-17 13:14 UTC, geggleto approved these changes

2017-08-17 13:18 UTC, akrabat commented
Rebased to fix conflicts

2017-08-17 13:25 UTC, merged