Minor perf improvement during error handling
slimphp/Slim pull request #2263
Opened 2017-07-17 15:54 UTC by Sam-Burns

Makes the error handling in the front controller run very slightly faster, by avoiding `call_user_func_array()`.

2017-07-17 17:11 UTC, silentworks commented on Slim/App.php
> +        return $handler(...$params);
Is this a PHP 7 feature?

2017-07-17 17:14 UTC, chadicus commented on Slim/App.php
> +        return $handler(...$params);
[PHP 5.6](http://php.net/manual/en/functions.arguments.php#functions.variable-arg-list)

2017-07-17 22:47 UTC, Sam-Burns commented on Slim/App.php
> +        return $handler(...$params);
The build's passing in PHP 5.6-7.1 and HHVM - think we're all good on that front.

2017-07-17 23:49 UTC, RyanNerd commented on Slim/App.php
> +        return $handler(...$params);
Why are you using `return $handler(...$params);` for the `handleException()` method, but in the `handlePhpError()` method you implicitly list the parameters: `return $handler($request, $response, $e);`  ?

2017-07-18 06:20 UTC, akrabat requested changes

2017-07-18 06:20 UTC, akrabat commented on Slim/App.php
> +        return $handler(...$params);
Maybe refactor and replace the `$params` assignments with the `return $handler` call?

That way we can also lose the final `else`.

2017-07-18 20:44 UTC, RyanNerd commented
A couple of suggestions (thanks for your work so far):

Refactoring handleException to perhaps use the `switch` construct.

It also looks like you are missing the `elseif ($e instanceof SlimException)` logic in this PR:
The `SlimException` is implicitly thrown in the unit tests.

2017-09-21 07:22 UTC, akrabat commented
> It also looks like you are missing the `elseif ($e instanceof SlimException)` logic in this PR:
The `SlimException` is implicitly thrown in the unit tests.

In 4.x, there's no `SlimException`.

2017-09-21 07:24 UTC, merged