Separate routing from dispatching
slimphp/Slim pull request #2288
Opened 2017-08-13 14:24 UTC by akrabat

Move the routing to middleware so that the user can add it wherever they want it to be within the middleware stack. This gives us the new capability to allow for some middleware to run before routing and some after.

If the `Routing` middleware isn't added by the user, then automatically call it in `App::__invoke()` as a last resort.

Also, remove `determineRouteBeforeAppMiddleware` setting as it's no longer necessary.

2017-08-14 13:30 UTC, geggleto requested changes
Also will this not only affect Slim currently when you use the invoke method. We would need to make more changes to affect run?

2017-08-14 13:30 UTC, geggleto commented on Slim/Middleware/Routing.php
> +class Routing
We need a new name for this.

2017-08-14 13:30 UTC, geggleto commented on Slim/Middleware/Routing.php
> +    public function doRouting(ServerRequestInterface $request)
.............. 👎 you can... doBetter

2017-08-14 13:59 UTC, silentworks commented on Slim/Middleware/Routing.php
> +    public function doRouting(ServerRequestInterface $request)
Whats wrong with this?

2017-08-14 14:00 UTC, geggleto commented on Slim/Middleware/Routing.php
> +    public function doRouting(ServerRequestInterface $request)
doRouting ... surely we can come up with a better name :P

2017-08-14 17:05 UTC, akrabat commented on Slim/Middleware/Routing.php
> +class Routing
Any preference? `RoutingMiddleware` ?

2017-08-14 17:06 UTC, akrabat commented on Slim/Middleware/Routing.php
> +    public function doRouting(ServerRequestInterface $request)
`performRouting()` ?

2017-08-14 17:07 UTC, geggleto commented on Slim/Middleware/Routing.php
> +class Routing
I would prefer to have everything suffixed ...

2017-08-14 17:08 UTC, geggleto commented on Slim/Middleware/Routing.php
> +    public function doRouting(ServerRequestInterface $request)
`dispatchRequest` ?

2017-08-15 07:53 UTC, akrabat commented on Slim/Middleware/Routing.php
> +    public function doRouting(ServerRequestInterface $request)
Cant' be `dispatchRequest` as this code doesn't dispatch - it only performs the routing work and then we dispatch later.

2017-08-15 07:57 UTC, akrabat commented on Slim/Middleware/Routing.php
> +class Routing
Renamed to `RoutingMiddleware`

2017-08-17 07:57 UTC, silentworks commented on Slim/Middleware/Routing.php
> +    public function doRouting(ServerRequestInterface $request)
Maybe `prepare` or `perform` then?

2017-08-17 13:16 UTC, geggleto approved these changes

2017-08-17 13:19 UTC, akrabat commented
Rebased

2017-08-17 13:23 UTC, akrabat commented
Renamed `doRouting()` to `performRouting()`

2017-08-17 15:20 UTC, merged