Add 443 as SERVER_PORT(default) when request is https
slimphp/Slim pull request #2323
Opened 2017-10-31 22:12 UTC by juanpagfe

Hi.  I solved the #2318 issue. Just added a validation wich changes the default port when request is HTTPS to 443.

2017-11-01 09:09 UTC, akrabat requested changes
Some changes required as noted.

Also, please supply a unit test so that we don't regress your fix.

2017-11-01 09:09 UTC, akrabat commented on Slim/Http/Environment.php
> +                      ? 443 : 80;
Please use an `if` statement.

2017-11-01 09:09 UTC, akrabat commented on Slim/Http/Environment.php
> +        $defport = (isset($userData["HTTPS"]) ||
`["HTTPS"]` may contain the string `off`, which should use port 80.

2017-11-01 09:09 UTC, akrabat commented on Slim/Http/Environment.php
> +                    (isset($userData["SERVER_PROTOCOL"]) && substr($userData["SERVER_PROTOCOL"], 0, 5) === "HTTPS"))
[`SERVER_PROTOCOL`] will contain `HTTP/1.0`, `HTTP/1.1` or `HTTP/2`. It will never contain `HTTPS` and so please do not check this key.

2017-11-01 09:09 UTC, akrabat commented on Slim/Http/Environment.php
> +        $defport = (isset($userData["HTTPS"]) ||
Use single quoted strings if there's no variable interpolation.

2017-11-02 08:02 UTC, mahagr commented
Why not use `REQUEST_SCHEME` which is either `http` or `https`?

2017-11-02 15:05 UTC, akrabat commented
> Why not use `REQUEST_SCHEME` which is either `http` or `https`?

No reason that it also couldn't be checked. I hadn't heard of it, so didn't mention it.

2017-11-02 15:07 UTC, akrabat commented on Slim/Http/Environment.php
> +            'REQUEST_SCHEME'       => 'http',
If you are going to put `REQUEST_SCHEME` here, then it needs to be either `http` or `https` …

2017-11-03 17:01 UTC, akrabat requested changes

2017-11-03 17:01 UTC, akrabat commented on phpunit.xml.dist
> +         stopOnFailure="true"
Please remove this change.

2017-11-03 18:16 UTC, akrabat approved these changes

2017-11-03 18:18 UTC, merged

2017-11-03 18:19 UTC, akrabat commented
Thank you @juanpagfe  :)

2017-11-04 08:26 UTC, akrabat commented
@juanpagfe Fancy creating a similar PR for https://github.com/slimphp/Slim-Http ?

2017-11-06 06:35 UTC, mahagr commented
@akrabat Any change making the same change into Uri class:

https://github.com/slimphp/Slim/blob/3.x/Slim/Http/Uri.php#L169-L170

Mostly because of HTTPS isn't always available.

2017-11-06 07:43 UTC, akrabat commented
@mahagr Which web server doesn’t set `HTTPS` when the connection is over TLS?

2017-11-06 08:32 UTC, mahagr commented
See discussion in:

https://github.com/getgrav/grav/commit/a9c82710a6f33b636a84cc42e4d0b1964d7c1483

2017-11-06 11:18 UTC, juanpagfe commented
@akrabat Of course, I'll create a PR in a minute.