Add HTTP method override middleware
slimphp/Slim pull request #2329
Opened 2017-11-04 23:16 UTC by danopz

HTTP method overriding is already removed from SLim as it was present in `Request::getMethod()`.
So I just added a middleware to resolve #2040.

Resolves #2040

2017-11-26 16:33 UTC, akrabat requested changes
There's no point in calling `withMethod()` if no method override is found. Please refactor appropriately.

2017-11-26 23:15 UTC, danopz commented
Done

2017-12-23 10:39 UTC, akrabat approved these changes

2017-12-23 10:42 UTC, merged

2017-12-23 10:42 UTC, akrabat commented
Thanks.