4.x Error Middleware
slimphp/Slim pull request #2398
Opened 2018-02-14 18:30 UTC by l0gicgate

**Preface**
The original PR #2222 was closed and some of the concepts and code will be implemented in this PR. 

**Description**
This PR eliminates all native error handlers and replaces it with `ErrorMiddleware` which handles all errors and provides multiple different renderers (HTML, XML, JSON, Plain Text) to enhance error display.

**Status**
Work in progress
- [x] Remove Existing Error Handling
- [ ] Implement Error Middleware
- [ ] Implement supporting tests
- [ ] Discussion and Code Review.

2018-02-15 22:54 UTC, asheliahut requested changes
Just some thoughts.

2018-02-15 22:54 UTC, asheliahut commented on Slim/App.php
> +        if (is_null($this->request)) {
`null === $this->request` is better here no overhead of function call.

2018-02-15 22:54 UTC, asheliahut commented on Slim/App.php
> +        if (is_null($routeInfo)) {
should stay ===

2018-02-15 22:54 UTC, asheliahut commented on Slim/Error/Renderers/HtmlErrorRenderer.php
> +        } else {
you can just return before the else and have this html set as a second return lowering cyclomatic complexity by 1.

2018-02-15 22:54 UTC, asheliahut commented on Slim/Error/Renderers/HtmlErrorRenderer.php
> +        if (($code = $exception->getCode())) {
if someone passes an exception code of 0 this will never execute.

2018-02-15 22:54 UTC, asheliahut commented on Slim/Error/Renderers/HtmlErrorRenderer.php
> +        if (($message = $exception->getMessage())) {
if someone sets a message of '0' it also will fail to run.

2018-02-15 22:54 UTC, asheliahut commented on Slim/Error/Renderers/PlainTextErrorRenderer.php
> +        if ($code = $e->getCode()) {
what about 0 here too

2018-02-15 22:54 UTC, asheliahut commented on Slim/Error/Renderers/PlainTextErrorRenderer.php
> +        if ($message = $e->getMessage()) {
and '0' here too

2018-02-15 22:54 UTC, asheliahut commented on Slim/Error/Renderers/XmlErrorRenderer.php
> +                $xml .= "    <line>" . $e->getLine() . "</line>\n";
May want to exchange \n for . PHP_EOL for working with windows support.

2018-02-15 22:54 UTC, asheliahut commented on Slim/Exception/HttpException.php
> +            parent::__construct($details);
you can just return the parent constructor otherwise do $this->details = $details
thus removing the else.

2018-02-15 22:54 UTC, asheliahut commented on Slim/Exception/HttpNotAllowedException.php
> +            } elseif (is_string($allowedMethods)) {
this can be an if and not an else if because of the return will stop it anyways.

2018-02-15 22:54 UTC, asheliahut commented on Slim/Exception/HttpNotAllowedException.php
> +        if (is_null($this->details)) {
null === $this->details

2018-02-15 22:54 UTC, asheliahut commented on Slim/Exception/HttpNotFoundException.php
> +    protected $description = 'The requested resource could not be found. Please verify URI and try again.';
Please verify the URI and try again.

2018-02-15 22:54 UTC, asheliahut commented on Slim/Handlers/AbstractErrorHandler.php
> + * It outputs the error message and diagnostic information in either JSON, XML,
either -> one of the following

2018-02-15 22:54 UTC, asheliahut commented on Slim/Handlers/AbstractErrorHandler.php
> +        if ((!is_null($renderer) && !class_exists($renderer))
null ===  $renderer

2018-02-15 22:54 UTC, asheliahut commented on Slim/Handlers/AbstractErrorHandler.php
> +        if (is_null($renderer)) {
null === $renderer

2018-02-15 22:54 UTC, asheliahut commented on Slim/Handlers/AbstractErrorHandler.php
> +        } elseif ($this->exception instanceof HttpException) {
change to if because of return

2018-02-15 22:54 UTC, asheliahut commented on Slim/Handlers/AbstractErrorHandler.php
> +        error_log($error);
I feel like this error log should also be able to take in an outside error logging, as in be able to take in a logger middleware of some kind.

2018-02-15 22:54 UTC, asheliahut commented on Slim/Handlers/ErrorHandler.php
> + * It outputs the error message and diagnostic information in either
either-> one of the following

2018-02-15 22:54 UTC, asheliahut commented on Slim/Middleware/ErrorMiddleware.php
> +            if (!is_null($request)) {
=== null

2018-02-15 22:54 UTC, asheliahut commented on Slim/Middleware/RoutingMiddleware.php
> +        if (!is_null($exception)) {
!=== null

2018-02-15 22:54 UTC, asheliahut commented on Slim/Error/AbstractErrorRenderer.php
> + * It outputs the error message and diagnostic information in either JSON, XML,
either should be "one of the following"

2018-02-15 23:48 UTC, l0gicgate commented
Thank you @asheliahut for the code review. I'm aware this is a large PR and I really appreciate you going through everything. I have made the suggested changes besides the suggestion you made for the `AbstractErrorHandler::logError()` method, If people want to implement logging they can simply extend the class and replace the `::logError()` method. That's the main reason why I've left it abstract.

2018-02-17 08:35 UTC, odan commented on Slim/Error/Renderers/XmlErrorRenderer.php
> +                $xml .= "    <line>" . $e->getLine() . "</line>\n";
I'm developing under windows and linux and if I would run my api integration test under windows the tests would fail because the response is not the same like under linux. So please never use PHP_EOL because it will complicate thinks, especially in combination with windows and integration tests.

2018-02-17 10:32 UTC, odan commented on Slim/Error/Renderers/PlainTextErrorRenderer.php
> +        $text = 'Slim Application Error:' . PHP_EOL;
Use `\n` instead of `PHP_EOL` to make integration tests compatible with windows.

2018-02-17 10:36 UTC, odan commented on Slim/Handlers/AbstractErrorHandler.php
> +     * @throws \RuntimeException
Add `use RuntimeException` on top to remove the backslash.

2018-02-17 10:39 UTC, odan commented on Slim/Handlers/AbstractErrorHandler.php
> +        if ((
There'd be plenty of room to put this statement in one line.
`if (($renderer !== null && !class_exists($renderer)) {`

2018-02-17 10:41 UTC, odan commented on Slim/Handlers/AbstractErrorHandler.php
> +        $e = $this->exception;
This extra variable ($e) is not really necessary.

2018-02-17 10:43 UTC, odan commented on Slim/Middleware/ErrorMiddleware.php
> +     * @param string $type
What for values can be passed here?

2018-02-17 10:53 UTC, odan commented
Hi! 

I have some questions / ideas according to this PR and the error handling in general.

1) If Slim 4 will provide a new Error middleware like in this PR, why do we still need the `setErrorHandler()` and `setDefaultErrorHandler` methods in the App class? There should be only one style how to add middleware to the stack and not multiple different methods. This is important, because I want to decide in which order I place my middleware handlers. 

2) I don't like the PHP_EOL magic constant because the response will be different on windows/linux. The Response should be **exactly** the same for all platforms.

2018-02-17 12:42 UTC, odan commented
The name of the middleware `ErrorMiddleware` implies that it handles PHP errors. But in PHP there is a small difference between Exceptions and Errors. If this middleware handles "only" Exceptions and no "Errors" then the it should be renamed to "ExceptionMiddleware".

The question how to handle PHP [errors](http://php.net/manual/de/class.error.php) (extended from Throwable)? Are you planning a new separate Middleware (e.g. ErrorMiddleware) or a generic "ThrowableMiddleware" for Exceptions  **and** Errors together?

2018-02-17 19:55 UTC, designermonkey commented on Slim/Interfaces/ErrorRendererInterface.php
> +    public function __construct($exception, $displayErrorDetails);
Interfaces should not have a constructor as you are limiting the ability to define implementation detail vs defining expected behaviour.

Instead, your methods `render` and `renderWithBody` should accept the exception instance.

2018-02-17 20:00 UTC, l0gicgate commented
@odan 

- I am going to replace all instances of `PHP_EOL` to `\n`. Thanks for pointing that out.
- The `App` class does not contain `setErrorHandler()` and `setDefaultErrorHandler()` anymore. The first commit on this PR removes all that.
- Definitely open for proper naming suggestion for the middleware's name. It does handle both `Exception` and `Throwble` by default.

Thank you for reviewing this PR!

2018-02-17 20:01 UTC, l0gicgate commented on Slim/Interfaces/ErrorRendererInterface.php
> +    public function __construct($exception, $displayErrorDetails);
Thank you for pointing that out, I will refactor the interface accordingly!

2018-02-17 20:01 UTC, l0gicgate commented on Slim/Middleware/ErrorMiddleware.php
> +     * @param string $type
I don't understand your question. Can you clarify?

2018-02-17 20:10 UTC, edudobay commented
Hi! As I started to point out at #2393, I believe that there should be a separate `writeToErrorLog` (or similar) setting, that doesn’t need to subordinate to `displayErrorDetails`. A couple reasons for that:

* Newcomers might be confused when they turn of display of error details and things stop going to the error log.
* Anyways we might need to keep a log of errors even though they were displayed to the client (maybe the client was an API so we couldn’t really see the output).
* Writing to a log and rendering the error to the client seem like separate concerns to me. These could even be dealt with by separate classes; but anyway it seems to me that it would be more logical to have separate settings for separate (independent) behaviors.

If you agree with these concerns, you can refer to #2393 for some remarks I’ve already made and I’ll be happy to help with the implementation. (I already have a draft but it is written for Slim 3.)

2018-02-17 20:43 UTC, designermonkey commented
I think this is an awesome piece of work, and definitely the direction Slim should be going.

I left a comment, but I have a couple of points to raise; not complaints, more architectural ideas.

Looking at the `AbstractRenderer` and it's constructor, I see there is a boolean passed as an argument. Generally when passing a boolean, it's a sure sign that there are in fact two concerns being addressed by the class/method, and therefore a refactor in the making.

Maybe we could look at renderers like `RendersHtmlErrorsWithDetails` and `RendersHtmlErrorsWithoutDetails`? This is a strategy in effect, and can be handled by the container based on a more global config option, rather than passing the boolean `displayErrorDetails` around.

2018-02-17 20:47 UTC, l0gicgate commented
@edudobay Thank you for your suggestions. I will refactor `AbstractErrorHandler` accordingly.

`ErrorMiddleware` will take 2 parameters for the constructor `$displayErrorDetails` and `$logErrors` which will both be passed down to the default `ErrorHandler` that Slim ships with.

I will also implement a way to pass a custom callable to `ErrorHandler` so it stubs the default `error_log()` usage.

2018-02-17 21:39 UTC, l0gicgate commented
@edudobay as per the commits after our discussion. The error logging has been decoupled from `displayErrorDetails`. I updated the PR documentation to reflect how custom logging can be done as well.

2018-02-17 21:42 UTC, l0gicgate commented
@designermonkey the whole reason for having standalone error renderers is so they can be used by the end user as well if they decide to implement their own error handlers. Using global values from the containers would bind those renderers to the container which is not something I want to do. Am I misunderstanding what you're proposing?

2018-02-17 22:01 UTC, designermonkey commented
@l0gicgate I'm just generally stating that boolean values as constructor and method arguments is a code smell, and should be refactored in some way. The suggestion of container use was only an idea of how. :)

2018-02-17 22:01 UTC, odan commented
Maybe mixing error handling error logging violentes SRP. What do you think about splitting this into 2 Middleware classes? (Just an idea)

For example. 

1. `new ExceptionMiddleware(bool $displayErrorDetails)`
2. `new LogExceptionMiddleware($logger)`

Log all exceptions from your middlewares. When your middleware throw exception this middleware catch it, log it and throw again. You will newer miss any exception. [Example](https://github.com/php-middleware/log-exceptions/blob/master/src/LogExceptionMiddleware.php)

2018-02-17 22:03 UTC, designermonkey commented
@odan I would think that logging is a form of exception handling in itself. Recently I've been using messaging patterns more, and message handling can have more than one handler, so maybe a direction to go? Exception handling could indeed be a kind of middleware pipe allowing multiple handlers?

2018-02-17 22:07 UTC, odan commented
@designermonkey Well, it's still possible to log and handle the error in the same callback. Then we could everything there. For example:

```php
$errorMiddleware = new ErrorMiddleware(false);

$handler = function ($req, $res, $exception, $displayErrorDetails) {
   // get the logger and log something.
    $logger->error(...);
    return $res->withJson(['error' => 'Caught MyNamedException']);
}
$errorMiddleware->setErrorHandler(MyNamedException::class, $handler);
$app->add($errorMiddleware);
```

2018-02-17 22:07 UTC, l0gicgate commented
@designermonkey I refactored the `ErrorRendererInterface` after our discussion in this (commit)[https://github.com/slimphp/Slim/pull/2398/commits/595f9819cb137d5725473aa898b134872e62dd2a]. I however did not split the methods for displaying/not displaying error details.

2018-02-18 23:49 UTC, edudobay commented on Slim/Handlers/AbstractErrorHandler.php
> +        $error = $renderer->render($this->exception, $this->displayErrorDetails);
Maybe the details should *always* be displayed in the error log? To me it doesn’t make sense to log a generic "Application error" without details.

(Maybe we are starting to cross boundaries and violating SRP as @odan pointed out?)

2018-02-19 00:28 UTC, l0gicgate commented on Slim/Handlers/AbstractErrorHandler.php
> +        $error = $renderer->render($this->exception, $this->displayErrorDetails);
You do have a point. I can modify this so it’s always displaying the error details when writing to log if everyone is in favor of this option!

@odan @designermonkey @akrabat @asheliahut @geggleto

2018-02-19 08:36 UTC, akrabat commented
> /*
>  * The routing middleware should always be added first
>  * before the error handling middleware is added
>  */

Why? I want the error handling middleware to be the outermost middleware as there will be other middleware before routing that I want the error handler to pick up.

2018-02-19 10:03 UTC, odan commented on Slim/Handlers/AbstractErrorHandler.php
> +        $error = $renderer->render($this->exception, $this->displayErrorDetails);
On a production server I have to log all errors (into a file), but for security reasons I am not allowed to show the users any error details. Therefore, it is still necessary to be able to configure both options (displayErrorDetails and logging) independently of each other.

2018-02-19 10:13 UTC, akrabat commented on Slim/Handlers/AbstractErrorHandler.php
> +        $error = $renderer->render($this->exception, $this->displayErrorDetails);
For more advanced requirements, I expect that the user should be able to easily replace Slim's error handling with their own.

I don't want this component to turn into a massive thing as we're _Slim_! However, we should be reasonably flexible.

2018-02-19 19:44 UTC, l0gicgate commented
@akrabat what I meant by that is `ErrorMiddleware` should be the last one to be added. In the example `RoutingMiddleware` should be added first, but I don't mean that it should be added first in your whole application.

2018-02-19 19:52 UTC, l0gicgate commented on Slim/Handlers/AbstractErrorHandler.php
> +        $error = $renderer->render($this->exception, $this->displayErrorDetails);
So how about I decouple `$displayErrorDetails` from the logging and add another parameter `$logErrorDetails` which can be enabled or disabled. So for instance you may not want to display the error details to the end user but you may want to have them displayed in your log.

2018-02-19 21:08 UTC, odan commented on Slim/Handlers/AbstractErrorHandler.php
> +        $error = $renderer->render($this->exception, $this->displayErrorDetails);
@l0gicgate Sounds good

2018-02-19 21:17 UTC, l0gicgate commented on Slim/Handlers/AbstractErrorHandler.php
> +        $error = $renderer->render($this->exception, $this->displayErrorDetails);
@odan I've implemented `$logErrorDetails` in this [commit](https://github.com/slimphp/Slim/pull/2398/commits/897958f4e6efb6d297b098ada9d9cdc01013fe92)

2018-02-25 09:58 UTC, akrabat commented on Slim/App.php
> +     * @codeCoverageIgnore
Why are we ignoring code coverage for methods in App?

2018-02-25 10:07 UTC, akrabat commented on Slim/App.php
> +    protected $request;
I do not want $request or $response as properties on App. They were intentionally removed from Slim 3's DIC because they are immutable and people use them as if they aren't.

This also means that I don't want `set/getRequest()` and `set/getResponse()`.

Also, `run()` and `process()` are separate for a reason: it allows someone to inject their own request and response when running Silm.

2018-02-25 11:39 UTC, akrabat requested changes
A number of bits and bobs in here to look at @l0gicgate.

If you'd like me to raise a PR against this one addressing them, let me know.

2018-02-25 11:39 UTC, akrabat commented on Slim/Middleware/ErrorMiddleware.php
> +     */
Add a gap between each property. It just looks nicer. This applies to all files.

2018-02-25 11:39 UTC, akrabat commented on Slim/Middleware/ErrorMiddleware.php
> +        $this->response = $response;
Do not store response. Each renderer should return a response that they have created.

2018-02-25 11:39 UTC, akrabat commented on Slim/Middleware/RoutingMiddleware.php
> +            $exception = new HttpNotFoundException();
Call ` $exception->setRequest($request);` and then `throw` directly here.

2018-02-25 11:39 UTC, akrabat commented on Slim/Middleware/RoutingMiddleware.php
> +            $exception->setAllowedMethods($routeInfo[1]);
Call ` $exception->setRequest($request);` and then `throw` directly here.

I know it's a duplication from above, but will be clearer to read and remove the test for not null below.

2018-02-25 11:39 UTC, akrabat commented on Slim/Middleware/ErrorMiddleware.php
> +        if (method_exists($exception, 'getRequest')) {
Test for an instance of `HttpException`. That way we can be sure that the Request object in getRequest() is a PSR7 Request object.

2018-02-25 11:39 UTC, akrabat commented on Slim/Middleware/ErrorMiddleware.php
> +            if ($request !== null) {
Can we make `HttpException`'s constructor require a `Request` object? Then we don't need the null test here.

2018-02-25 11:39 UTC, akrabat commented on Slim/Handlers/AbstractErrorHandler.php
> +            if ($current === 'text/plain' && $count > 1) {
I'm not sure about this. Conceptually, if the client has set `text/plain` first, then it should win. Is there a major browser which sets `text/plain` first or something?

2018-02-25 11:39 UTC, akrabat commented on Slim/Handlers/AbstractErrorHandler.php
> +        ResponseInterface $response,
Don't need a Response here. The renderer should create its own.

2018-02-25 11:39 UTC, akrabat commented on Slim/Middleware/ErrorMiddleware.php
> +        $this->defaultErrorHandler = new ErrorHandler($logErrors, $logErrorDetails);
I don't think that we should instantiate an ErrorHandler here. More often than not, we won't need it.

2018-02-25 11:39 UTC, akrabat commented on Slim/Middleware/ErrorMiddleware.php
> +        $this->defaultErrorHandler = new ErrorHandler($logErrors, $logErrorDetails);
Why are `$logErrors` and `$logErrorDetails` passed directly to the ErrorHandler directly and not passed in via `__invoke` like `$displayErrorDetails` is?

I can imagine that if I register my own ErrorHandler, I'd like the option to implement logging of errors as per the user's configuration of the error middleware.

2018-02-25 11:39 UTC, akrabat commented on Slim/Middleware/ErrorMiddleware.php
> +        if (isset($this->handlers[$type]) && is_callable($this->handlers[$type])) {
Ideally, we should integrate the container and collect from there, so that we can lazily instantiate ErrorHandler classes.

2018-02-25 11:39 UTC, akrabat commented on Slim/Middleware/ErrorMiddleware.php
> +        return $this->defaultErrorHandler;
Related, would be nice to collect from the container rather than having to have it instantiated every request.

2018-02-25 11:39 UTC, akrabat commented on Slim/Handlers/AbstractErrorHandler.php
> +        if ($renderer !== null
Don't just test here. If the `$renderer` is not null, then we can instantiate it and return it within this `if()` statement. That way we can test using `instancepf ErrorRendererInterface` and we don't have to check for `$renderer === null` later in the method.

2018-02-25 11:39 UTC, akrabat commented on Slim/Handlers/AbstractErrorHandler.php
> +        if ($this->method === 'OPTIONS') {
Probably not this PR, but I think we should handle Options in its own middleware or in App or Route directly.

2018-02-25 11:39 UTC, akrabat commented on Slim/Handlers/AbstractErrorHandler.php
> +        $body = $this->renderer->renderWithBody($this->exception, $this->displayErrorDetails);
The renderer should return a response that's configured with the content-type correct header. Just add the status and we're good to go.

2018-02-25 11:39 UTC, akrabat commented on Slim/Handlers/AbstractErrorHandler.php
> +        error_log($error);
In general, I agree. A separate PR after this could allow for handling a PSR3 logger.

2018-02-25 11:39 UTC, akrabat commented on Slim/Error/AbstractErrorRenderer.php
> +        return $body;
Renderers should return a Response. As such, I'm not sure what an abstract implementation looks like, so this can probably be removed.

2018-02-25 11:39 UTC, akrabat commented on Slim/Error/Renderers/HtmlErrorRenderer.php
> +    public function render($exception, $displayErrorDetails)
Return a Response.

2018-02-25 11:39 UTC, akrabat commented on Slim/Error/Renderers/JsonErrorRenderer.php
> +    public function render($exception, $displayErrorDetails)
Return a Response.

2018-02-25 11:39 UTC, akrabat commented on Slim/Error/Renderers/JsonErrorRenderer.php
> +        return json_encode($error, JSON_PRETTY_PRINT);
Can we use `JSON_PRETTY_PRINT| JSON_UNESCAPED_SLASHES` please?

2018-02-25 11:39 UTC, akrabat commented on Slim/Error/Renderers/PlainTextErrorRenderer.php
> +    public function render($exception, $displayErrorDetails)
Return a Response.

2018-02-25 11:39 UTC, akrabat commented on Slim/Error/Renderers/XmlErrorRenderer.php
> +    public function render($exception, $displayErrorDetails)
Return a Response.

2018-02-25 11:39 UTC, akrabat commented on Slim/Exception/HttpBadGatewayException.php
> +class HttpBadGatewayException extends HttpException
Please remove this Exception. It's not a common enough use-case to my mind.

2018-02-25 11:39 UTC, akrabat commented on Slim/Exception/HttpException.php
> +    public function __construct($details = null)
Can we make Request the first constructor parameter (required)? I can't think of a downside.

2018-02-25 11:39 UTC, akrabat commented on Slim/Exception/HttpException.php
> +    protected $response = null;
No need for `$response`. Create one if you need one.

2018-02-25 11:39 UTC, akrabat commented on Slim/Exception/HttpException.php
> +    public function __construct($details = null)
What's the difference between details, title and description?

2018-02-25 11:39 UTC, akrabat commented on Slim/Exception/HttpNotAllowedException.php
> +class HttpNotAllowedException extends HttpException
Rename to `HttpMethodNotAllowedException`.

2018-02-25 11:39 UTC, akrabat commented on Slim/Handlers/AbstractErrorHandler.php
> +        if ($this->exception instanceof HttpNotAllowedException) {
As the exception should return a response, this can go into the exception itself.

2018-02-25 11:39 UTC, akrabat commented on Slim/Handlers/ErrorHandler.php
> +class ErrorHandler extends AbstractErrorHandler
Would rather have an interface and rename `AbstractErrorHandler` to `ErrorHandler`

2018-02-25 11:39 UTC, akrabat commented on Slim/Interfaces/ErrorHandlerInterface.php
> +        ResponseInterface $response,
Response not required.

2018-02-25 11:39 UTC, akrabat commented on Slim/Interfaces/ErrorRendererInterface.php
> +interface ErrorRendererInterface
I think we just need `render` which returns a response.

2018-02-26 07:32 UTC, l0gicgate commented on Slim/App.php
> +     * @codeCoverageIgnore
Removed and added tests for those methods.

2018-02-26 07:32 UTC, l0gicgate commented on Slim/App.php
> +    protected $request;
Removed and modified run() signature to take in an optional $request parameter for test purposes.

2018-02-26 07:49 UTC, l0gicgate commented on Slim/Middleware/ErrorMiddleware.php
> +     */
Done.

2018-02-26 07:50 UTC, l0gicgate commented on Slim/Middleware/ErrorMiddleware.php
> +        $this->response = $response;
Done.

2018-02-26 07:50 UTC, l0gicgate commented on Slim/Middleware/RoutingMiddleware.php
> +            $exception = new HttpNotFoundException();
Done.

2018-02-26 07:50 UTC, l0gicgate commented on Slim/Middleware/RoutingMiddleware.php
> +            $exception->setAllowedMethods($routeInfo[1]);
Done.

2018-02-26 07:50 UTC, l0gicgate commented on Slim/Middleware/ErrorMiddleware.php
> +        if (method_exists($exception, 'getRequest')) {
Done.

2018-02-26 07:55 UTC, l0gicgate commented on Slim/Middleware/ErrorMiddleware.php
> +            if ($request !== null) {
I don't think that's a good idea. Users might be using these exceptions within their applications and having to keep request in scope all the time when throwing one of these named exceptions is annoying. I use these exceptions a lot in the API that I am building at the moment and I would be hindered by having to pass $request every time.

2018-02-26 07:57 UTC, akrabat commented on Slim/Middleware/ErrorMiddleware.php
> +            if ($request !== null) {
Okay. Accepted for now. I'm mildly concerned that you're throwing HTTP exceptions from somewhere where you don't have a request object, but it's your architecture :)

2018-02-26 08:00 UTC, l0gicgate commented on Slim/Handlers/AbstractErrorHandler.php
> +        ResponseInterface $response,
Done.

2018-02-26 08:00 UTC, l0gicgate commented on Slim/Middleware/ErrorMiddleware.php
> +        $this->defaultErrorHandler = new ErrorHandler($logErrors, $logErrorDetails);
Refactored.

2018-02-26 08:01 UTC, l0gicgate commented on Slim/Middleware/ErrorMiddleware.php
> +        $this->defaultErrorHandler = new ErrorHandler($logErrors, $logErrorDetails);
Absolutely right. Refactored.

2018-02-26 08:59 UTC, l0gicgate commented on Slim/Error/Renderers/JsonErrorRenderer.php
> +        return json_encode($error, JSON_PRETTY_PRINT);
Done.

2018-02-26 08:59 UTC, l0gicgate commented on Slim/Exception/HttpBadGatewayException.php
> +class HttpBadGatewayException extends HttpException
Removed.

2018-02-26 08:59 UTC, l0gicgate commented on Slim/Exception/HttpException.php
> +    public function __construct($details = null)
Refactored as discussed.

2018-02-26 08:59 UTC, l0gicgate commented on Slim/Exception/HttpException.php
> +    protected $response = null;
Done.

2018-02-26 09:00 UTC, l0gicgate commented on Slim/Exception/HttpNotAllowedException.php
> +class HttpNotAllowedException extends HttpException
Done.

2018-02-26 09:00 UTC, l0gicgate commented on Slim/Handlers/ErrorHandler.php
> +class ErrorHandler extends AbstractErrorHandler
Done.

2018-02-26 09:01 UTC, l0gicgate commented on Slim/Interfaces/ErrorHandlerInterface.php
> +        ResponseInterface $response,
Refactored.

2018-02-26 09:07 UTC, l0gicgate commented on Slim/Exception/HttpException.php
> +    public function __construct($details = null)
This may be a bit too fancy. I could concatenate `$title` and `$description` and concatenate it into `$message`. I really outdid myself here 😂 

```php
class HttpForbiddenException extends HttpSpecializedException
{
    protected $code = 403;
    protected $message = 'Forbidden.';
    protected $title = '403 Forbidden';
    protected $description = 'You are not permitted to perform the requested operation.';
}
```

Can we settle on:
```php
class HttpForbiddenException extends HttpSpecializedException
{
    protected $code = 403;
    protected $message = 'Forbidden. You are not permitted to perform the requested operation.';
}
```

Thoughts?

2018-02-26 09:41 UTC, l0gicgate commented on Slim/Interfaces/ErrorHandlerInterface.php
> +        ResponseInterface $response,
Actually, what if during the middleware progression a user did attach headers to the response, example if a CORS middleware appended headers, wouldn't we want to have the response object that reflects the correct state at the time the time the exception was thrown?

2018-02-26 09:49 UTC, akrabat commented on Slim/Interfaces/ErrorHandlerInterface.php
> +        ResponseInterface $response,
Where does it come from given that the error handler is called from the catch() of the Middleware and that we won't have $response passed into the middleware in PSR-15?

2018-03-12 20:01 UTC, merged