4.x New Dispatcher & Dispatcher Results
slimphp/Slim pull request #2405
Opened 2018-02-23 22:20 UTC by l0gicgate

As per #2399 

As discussed on Slack, there are a few issues with the way `FastRoute\Dispatcher` returns information after a route has been dispatched.

**Issues**
- `FastRoute\Dispatcher::dispatch()` returns an array with an inconsistent structure
- It only appends allowed methods to the return value when no allowed methods have been found on the dispatched route.

**Changes**
- `routeInfo` now deprecated and replaced with `dispatcherResults`
- `DispatcherResults` is an immutable object instantiated by the Slim Dispatcher which now offers a way to get all a route's allowed methods which was not accessible before via `FastRoute\GroupCountBased\Dispatcher`

**Usage**
```php
use Slim\App;

$app = new App();
$app->get('/foo', function (Request $request, Response $response) {
    $dispatcherResults = $request->getAttribute('dispatcherResults');
    $uri = $dispatcherResults->getUri();
    $method = $dispatcherResults->getMethod();
    $allowedMethods = $dispatcherResults->getAllowedMethods();
});
```

**Status**
- [X] Implement new Dispatcher & Dispatcher Results
- [X] Write supporting Dispatcher & Dispatcher Results tests
- [ ] Code Review & Discussion

2018-05-16 18:55 UTC, geggleto requested changes

2018-05-16 18:55 UTC, geggleto commented on Slim/Router.php
> +                'dispatcher' => '\\Slim\\Dispatcher',
We should use the class constant here

2018-05-16 18:55 UTC, geggleto commented on Slim/Router.php
> +                'dispatcher' => '\\Slim\\Dispatcher',
This however makes the app not extendable and a user cannot replace the dispatcher

2018-05-16 18:58 UTC, damianopetrungaro commented on Slim/DispatcherResults.php
> +     * Not Found = 0
What do you think about using an Enum for this `$routeStatus` or if it's an overhead use constants instead of comments for valid statuses?

2018-05-16 18:59 UTC, damianopetrungaro commented on Slim/DispatcherResults.php
> +        if ($urlDecode) {
Avoid nested statement:
```
if (!$urlDecode) {
	return $this->routeArguments;
}

$routeArguments = [];
foreach ($this->routeArguments as $key => $value) {
    $routeArguments[$key] = urldecode($value);
}

return $routeArguments;
```

2018-05-16 19:02 UTC, geggleto commented on Slim/DispatcherResults.php
> +     * Not Found = 0
It probably should be a class constant

2018-05-16 19:02 UTC, damianopetrungaro commented on Slim/Dispatcher.php
> +        if ($httpMethod === 'HEAD') {
Wdyt about adding `https://github.com/php-fig/http-message-util` to avoid hardcoded HTTP methods?

2018-05-16 19:04 UTC, geggleto commented on Slim/Dispatcher.php
> +        if ($httpMethod === 'HEAD') {
HTTP Methods don't change. I dont think we need to include a package for constants, we aren't javascript.

2018-05-16 19:06 UTC, l0gicgate commented on Slim/Router.php
> +                'dispatcher' => '\\Slim\\Dispatcher',
Actually the Router can be extended and this method overridden. When instantiating the RoutingMiddleware you can pass a router to it which could be the router of your choice. An alternative would be to pass settings to the Router constructor.

2018-05-16 19:08 UTC, damianopetrungaro commented on Slim/Dispatcher.php
> +        if ($httpMethod === 'HEAD') {
I always include it in for descriptive HTTP status codes and it contains have HTTP methods too.
Seen that is a FIG package I'm ok with it.
But I get your point of view so it's not a big deal 😄

2018-05-16 19:09 UTC, l0gicgate commented on Slim/DispatcherResults.php
> +     * Not Found = 0
The routeStatus is what comes from Fastroute. We can convert those to constants. Should the constants be on the Dispatcher or Dispatcher results and what should they be named? FOUND, NOT_FOUND, NOT_ALLOWED?

2018-05-16 19:09 UTC, damianopetrungaro commented on Slim/DispatcherResults.php
> +     * Not Found = 0
Yup, class constant or Enum will be more explicit so for me both are good.

2018-05-16 19:15 UTC, damianopetrungaro commented on Slim/DispatcherResults.php
> +     * Not Found = 0
1: `FOUND`, `NOT_FOUND`, `NOT_ALLOWED` sounds good to me.
2: You use them in `DispatcherResults` so it may be the right place (imho use an Enum and inject it is the best approach)

2018-05-16 19:32 UTC, l0gicgate commented on Slim/DispatcherResults.php
> +     * Not Found = 0
Actually, no need to make changes. This PR extends FastRoute\Dispatcher\GroupCountBased class which implements  FastRoute\Dispatcher interface which has those constants. They can be used as Slim\Dispatcher::FOUND, Slim\Dispatcher::NOT_FOUND, Slim\Dispatcher::NOT_ALLOWED

I will amend the comment in DispatcherResults to reference where those integers come from.

2018-05-16 19:49 UTC, l0gicgate commented on Slim/Dispatcher.php
> +        if ($httpMethod === 'HEAD') {
If anywhere, this should be on the Slim\Http package.

2018-05-16 19:52 UTC, damianopetrungaro commented on tests/RouterTest.php
> +        }, ['dispatcher' => '\\Slim\\Dispatcher']));
Use `Dispatcher::class` instead of hardcoded namespace, if it will change we have to change it in a lot of places

2018-05-16 21:32 UTC, damianopetrungaro commented on tests/RouterTest.php
> +        $this->assertInstanceOf('\Slim\Dispatcher', $dispatcher);
@l0gicgate  Here namespace too 😄

2018-05-16 21:33 UTC, damianopetrungaro commented on tests/RouterTest.php
> +        $this->assertInstanceOf('\Slim\Dispatcher', $prop->getValue($this->router));
@l0gicgate  Here namespace too 😄

2018-05-16 21:33 UTC, damianopetrungaro commented on tests/RouterTest.php
> +        $this->assertInstanceOf('\Slim\Dispatcher', $method->invoke($this->router));
@l0gicgate  Here namespace too 😄

2018-05-16 21:34 UTC, damianopetrungaro commented on tests/DispatcherTest.php
> +        return 'FastRoute\\DataGenerator\\GroupCountBased';
Are we including it as dependency?
We may use namespace here too instead of hardcoded 😄

2018-05-16 21:34 UTC, damianopetrungaro commented on tests/DispatcherTest.php
> +        return 'Slim\\Dispatcher';
@l0gicgate  Here namespace too 😄

2018-05-17 05:45 UTC, akrabat commented on Slim/Middleware/RoutingMiddleware.php
> +            default:
`default` should be last in a switch statement. Arguably, it should throw an Exception as it should never happen.

2018-05-17 05:45 UTC, akrabat commented on Slim/Dispatcher.php
> +        return $allowedMethods;
Should we be caching the list of allowed methods in an instance variable keyed by the function's parameters? It appears that we currently have to do this same work twice when we're in a method not allowed scenario.

2018-05-17 05:45 UTC, akrabat commented on Slim/DispatcherResults.php
> +    public function getRouteArguments($urlDecode = true)
Why would we not want to url decode the route arguments?

2018-05-17 06:01 UTC, l0gicgate commented on Slim/DispatcherResults.php
> +    public function getRouteArguments($urlDecode = true)
This is what is currently being done https://github.com/slimphp/Slim/blob/4.x/Slim/Middleware/RoutingMiddleware.php#L66

2018-05-17 06:03 UTC, l0gicgate commented on Slim/Dispatcher.php
> +        return $allowedMethods;
As per one of our previous discussions, this avoids the initial performance hit of looping through every single route. It is being returned on demand instead of initially doing it every time we dispatch. This is also the way Fastroute does it.

2018-05-17 06:04 UTC, l0gicgate commented on Slim/Middleware/RoutingMiddleware.php
> +            default:
What kind of exception would you like to be thrown here? Just a regular exception or RuntimeException

2018-05-17 06:04 UTC, akrabat commented on Slim/DispatcherResults.php
> +    public function getRouteArguments($urlDecode = true)
What I mean is that currently in Slim 3 it's not optional. Why is the choice a method parameter here?

2018-05-17 06:06 UTC, akrabat commented on Slim/Middleware/RoutingMiddleware.php
> +            default:
Runtime is fine as it should never happen :)

2018-05-17 06:13 UTC, akrabat commented on Slim/Dispatcher.php
> +        return $allowedMethods;
I understand that. 

Given `getAllowedMethods()` has been called, why don't we keep a copy of the calculated `$allowedMethods` in a local member variable, so that we don' have to do all the work again if `getAllowedMethods()` is called again with exactly the same parameters?

From what I can tell if we're in a Method Not Allowed situation, we call `getAllowedMethods()` on line 68 of `Dispatcher.php` and then again in line 83 of RoutingMiddleware.php, so it appears to me that we're doing the same work twice.

2018-05-17 08:36 UTC, akrabat commented on Slim/Router.php
> +     * @return DispatcherResults
We need to add

    $uri = rawurldecode($uri);

before calling the dispatcher's `dispatch()` in this method. Not sure if it should be a separate PR or not.

2018-05-17 20:01 UTC, l0gicgate commented on Slim/DispatcherResults.php
> +    public function getRouteArguments($urlDecode = true)
As per our discussion on slack, we're leaving this as is.

2018-05-17 20:02 UTC, l0gicgate commented on Slim/Router.php
> +     * @return DispatcherResults
This commit cc0c0b3 applies the requested change.

2018-05-17 20:29 UTC, damianopetrungaro commented
@l0gicgate btw before merging could you please squash all your commits?

2018-05-17 20:33 UTC, l0gicgate commented
@damianopetrungaro I'm not the one merging, @akrabat will take care of that!

2018-05-17 21:32 UTC, damianopetrungaro commented
You can do it also on your local branch:
`git rebase -i HEAD~{number of commit to squash}` and clean a little bit the history for this PR 😄

2018-05-18 07:37 UTC, akrabat commented
FWiW, I am not a fan of rebasing to clean history. Rebasing to remove a commit that's a typo fix is fine, but I personally prefer to see the route that was taken to get to where we are now.

2018-05-18 08:18 UTC, akrabat commented on Slim/Dispatcher.php
> +        if ($this->allowedMethods !== null) {
This will give the wrong answer if I do this:

    $methods1 = $o->getAllowedMethods('POST', '/foo');
    $methods2 = $o->getAllowedMethods('GET', '/bar');

At least, I think that `$methods2` will be the allowed methods for `/foo`

2018-05-19 20:17 UTC, l0gicgate commented on Slim/Dispatcher.php
> +        if ($this->allowedMethods !== null) {
You are correct, I made a mistake. I fixed this logic in latest commit. Good find!

2018-05-24 18:32 UTC, akrabat approved these changes

2018-05-24 19:02 UTC, merged

2018-05-24 19:56 UTC, damianopetrungaro commented
Great work @l0gicgate !