Add a redirect route shortcut
slimphp/Slim pull request #2425
Opened 2018-04-13 22:43 UTC by ellotheth

Per a short conversation with @akrabat.

(I'm blanket overwriting whatever status code the `ResponseInterface` has because I wasn't sure the flexibility in e.g. `Slim\Http\Response::withRedirect` is necessary at this level, but maybe it's worth keeping the behavior the same for consistency?)

2018-04-14 06:34 UTC, akrabat requested changes
Thanks @ellotheth!

Please add a test that ensures that `UriInterface` as `$destination` also works.

2018-04-14 06:36 UTC, akrabat commented
> (I'm blanket overwriting whatever status code the ResponseInterface has because I wasn't sure the flexibility in e.g. Slim\Http\Response::withRedirect is necessary at this level, but maybe it's worth keeping the behavior the same for consistency?)

This is correct. You should only change the response object on the way back anyway.

2018-04-14 07:10 UTC, ellotheth commented
@akrabat Righto, done!

2018-04-15 13:04 UTC, akrabat commented
Can you also do this against the `3.x` branch?

2018-04-16 10:20 UTC, ellotheth commented
Yup, and I'll add the docs. Should be be done by tomorrow night.

2018-04-19 18:45 UTC, akrabat approved these changes

2018-04-19 18:47 UTC, merged