Remove else conditions
slimphp/Slim pull request #2515
Opened 2018-10-03 02:45 UTC by omarkdev

This PR has the objective of removing `else` conditions in the code, either by applying the return early pattern or by adding ternary operators, this helps to reduce the cyclomatic complexity of the code

2018-10-08 04:57 UTC, vlakoff commented
People, please stop with this "no else" trend. The current code is fine.

Jeffrey Way should make an official statement to urge people to stop with this...

2018-10-08 06:01 UTC, akrabat commented
I'm mildly confused why you think someone who is involved with a completely different project should make such a statement rather than one of the leadership of this project :)

2018-10-08 06:04 UTC, akrabat requested changes

2018-10-08 06:04 UTC, akrabat commented on Slim/Container.php
> +            throw $exception;
👍

2018-10-08 06:04 UTC, akrabat commented on Slim/Http/Cookies.php
> +
Please revert as this ternary statement is harder to read.

2019-02-18 05:58 UTC, l0gicgate commented on Slim/Http/Cookies.php
> +
This would be a bit cleaner imo
```php
$expires = $properties['expires'];
$timestamp = is_string($expires) ? strtotime($expires) : (int) $expires;
```

2019-03-01 02:21 UTC, closed without merging