Remove binding of $this to group()
slimphp/Slim pull request #2560
Opened 2019-01-04 09:56 UTC by vaga

It's my first contribution. :tada: 

Closes #2559

2019-01-04 10:01 UTC, akrabat requested changes
Just a minor nitpick on a test name.

Also, please update the CHANGELOG

2019-01-04 10:01 UTC, akrabat commented on tests/AppTest.php
> +    public function testGroupWithBindingOfThis()
Please rename to `testGroupClosureIsBoundToThisClass`

2019-01-05 09:32 UTC, mbohal commented
@akrabat Should I update the https://github.com/slimphp/Slim-Website/tree/gh-pages-4.x to reflect this change? 
I'm not sure what is going to happen with the docs when Slim 4 gets released and I do not want to introduce any conflicts.

2019-01-05 11:09 UTC, akrabat commented
@mbohal Raise a PR against that branch please.

2019-01-23 07:48 UTC, merged

2019-01-23 07:49 UTC, akrabat commented
Thanks @vaga !