Refactor middleware into stack
slimphp/Slim pull request #2591
Opened 2019-02-23 05:05 UTC by bnf

Improve certain things:

- Do not hide container dependencies in the CallableResolverInterface
  getContainer method (this method is dropped now)
- Use a middleware stack instead of a queue, as slim used to use before #2555
- Use designated request handlers as kernel (as we know them from slim v3)
  instead of middlewares that ignore the second (RequestHandler) parameter
- Do not recreate middlewares in route/route-group middleware combination,
  rather chain middleware runners, thanks to the (now) proper use of
  RequestHandlerInterface
- Drop some helper middlewares, which is good as they were applicable only
  as internal middleware anyway. This logic is now handled in the middleware
  dispatcher for optimization reasons (because that handler
  create a RequestHandler wrapper for every middleware, it's most performant
  to include lazy/closure dispatch logic in the RequestHandler wrappers).
- DispatchMiddleware (and it's corresponding test) is moved into the
  Router which now acts as a PSR-15 RequestHandler
- Replace middleware related tests that test internal state (e.g. whether
  something is at the bottom of a list.) That is an implementation detail and
  should rather be verified by checking for proper operation
- Rename MiddlewareRunner to MiddlewareDispatcher, as it actually dispatches
  middlewares now
- Add more MiddlewareDispatcher tests

Fixes: #2590

2019-02-23 06:04 UTC, l0gicgate requested changes

2019-02-23 06:04 UTC, l0gicgate commented on Slim/MiddlewareDispatcher.php
> +        foreach ($middlewares as $middleware) {
This should be a separate setter. No logic should be in constructor.

2019-02-23 06:04 UTC, l0gicgate commented on Slim/MiddlewareDispatcher.php
> +    public function add($middleware): bool
This method should throw, not return a boolean.

2019-02-23 06:04 UTC, l0gicgate commented on Slim/MiddlewareDispatcher.php
> +        $this->tip = new class($middleware, $next) implements RequestHandlerInterface {
No class declaration inside functions like this, separate it, helps with testability as well.

2019-02-23 06:04 UTC, l0gicgate commented on Slim/MiddlewareDispatcher.php
> +        $this->tip = new class($middleware, $next, $this->container) implements RequestHandlerInterface {
Same comment as before, no class declaration inside functions like this.

2019-02-23 06:04 UTC, l0gicgate commented on Slim/MiddlewareDispatcher.php
> +        $this->tip = new class($middleware, $next) implements RequestHandlerInterface {
Same comment as before, no class declaration inside functions like this.

2019-02-23 06:04 UTC, l0gicgate commented on Slim/MiddlewareDispatcher.php
> +    public function addLazy(string $middleware)
This method name should be something else, `lazy` isn't a good word. Use `deferred` as we already agreed upon that and the terminology is used elsewhere in the repo.

2019-02-23 06:04 UTC, l0gicgate commented on Slim/MiddlewareDispatcher.php
> +            public function handle(ServerRequestInterface $request): ResponseInterface
All the logic contained in this method should be in a resolve method instead. Also, use the logic from `DeferredResolutionMiddleware` as @akrabat and I already agreed upon it.

2019-02-23 06:04 UTC, l0gicgate commented on Slim/Route.php
> +        ContainerInterface $container = null,
No null parameters before a required one, put `$invocationStrategy` first.

2019-02-23 06:04 UTC, l0gicgate commented on Slim/RouteGroup.php
> +    protected $middlewares = [];
The plural of `middleware` is still `middleware` and not `middlewares`. Please refactor that.

2019-02-23 06:04 UTC, l0gicgate commented on Slim/Router.php
> +     * @param ContainerInterface            $container
This should be `ContainerInterface|null` as well

2019-02-23 06:04 UTC, l0gicgate commented on Slim/Router.php
> +     * @var ContainerInterface
This should be `ContainerInterface|null`

2019-02-23 06:04 UTC, l0gicgate commented on Slim/Router.php
> +    public function handle(ServerRequestInterface $request): ResponseInterface
I'm not a huge fan of this, the Router's responsibility to handle requests. If @akrabat agrees then sure. I just don't think it belongs here.

2019-02-23 06:04 UTC, l0gicgate commented on tests/MiddlewareDispatcherTest.php
> +use Prophecy\Argument;
I don't see the need to add an entire mocking framework for these tests.

2019-02-23 06:04 UTC, l0gicgate commented on tests/MiddlewareDispatcherTest.php
> +use Pimple\Container as Pimple;
Just as an FYI, we are getting rid of Pimple entirely as a dev dependency. See PR #2587. You will need to refactor those tests.

2019-02-23 06:06 UTC, l0gicgate commented
Also please make sure that Travis CI build passes. Thank you.

2019-02-23 06:20 UTC, l0gicgate commented on Slim/MiddlewareDispatcher.php
> +     * @param ContainerInterface $container
This should be `ContainerInterface|null`

2019-02-23 06:21 UTC, l0gicgate submitted a review, later dismissed

2019-02-23 06:21 UTC, l0gicgate commented on Slim/MiddlewareDispatcher.php
> +     * @var ContainerInterface
This should be `ContainerInterface|null`

2019-02-23 06:29 UTC, bnf commented on Slim/MiddlewareDispatcher.php
> +        foreach ($middlewares as $middleware) {
Well, I disagree. Its fine to put constructing logic into the constructor.

2019-02-23 06:30 UTC, bnf commented on Slim/MiddlewareDispatcher.php
> +        $this->tip = new class($middleware, $next) implements RequestHandlerInterface {
No, testability is as easy as with seperate classes. Anonymous provide the same level of testability as closure, which we used for the use cases pre #2555.

2019-02-23 06:30 UTC, bnf commented on Slim/Router.php
> +     * @param ContainerInterface            $container
yup

2019-02-23 06:31 UTC, bnf commented on tests/MiddlewareDispatcherTest.php
> +use Prophecy\Argument;
It's part of phpunit. Really no issue here.

2019-02-23 06:32 UTC, bnf commented on Slim/Router.php
> +    public function handle(ServerRequestInterface $request): ResponseInterface
I'm a huge fan of this. The current approach of misusing middlewares for this is actually wrong. The router dispatches the request to a route. It is the RequestHandler.

2019-02-23 06:33 UTC, bnf commented on tests/MiddlewareDispatcherTest.php
> +use Pimple\Container as Pimple;
yes, these tests are copied from the previous DeferredDispatcher tests.. I included them this way to keep it reviewabl.
New tests (as in the second commit) therefore do not the pimple container, but rather mock the container (and request and everything) using prophecies.

2019-02-23 07:00 UTC, l0gicgate commented on Slim/MiddlewareDispatcher.php
> +        foreach ($middlewares as $middleware) {
Okay, well I'm requesting that you change it. Thank you.

2019-02-23 07:00 UTC, l0gicgate commented on Slim/MiddlewareDispatcher.php
> +        $this->tip = new class($middleware, $next) implements RequestHandlerInterface {
I'm requesting that you separate those classes. Thank you.

2019-02-23 07:02 UTC, l0gicgate commented on tests/MiddlewareDispatcherTest.php
> +use Prophecy\Argument;
If PHPUnit drops the dependency unexpectedly, then our build fails. So you have to include it in our `composer.json` if you're using it. It's a no from me, but @akrabat can make the final decision.

2019-02-23 07:07 UTC, l0gicgate commented on Slim/Router.php
> +    public function handle(ServerRequestInterface $request): ResponseInterface
Cool, @akrabat can make the call on this one.

2019-02-23 08:06 UTC, froschdesign commented on Slim/MiddlewareDispatcher.php
> +        foreach ($middlewares as $middleware) {
> No logic should be in constructor.

A condition is already a logic and is used in many constructors. 😉

2019-02-23 08:23 UTC, froschdesign commented on tests/MiddlewareDispatcherTest.php
> +use Prophecy\Argument;
@l0gicgate 
> If PHPUnit drops the dependency unexpectedly…

It's never _unexpectedly_. Everything else means you used the ["death star version constraint" on PHPUnit](https://thephp.cc/news/2017/02/death-star-version-constraint) in your `composer.json`. 😉

2019-02-23 08:24 UTC, l0gicgate commented on Slim/MiddlewareDispatcher.php
> +        foreach ($middlewares as $middleware) {
> A condition is already a logic and is used in many constructors. 😉

There's 2 constructors in this entire repository with an if condition. I would like to keep the constructors free of logic as much as possible.

2019-02-23 08:32 UTC, bnf commented on tests/MiddlewareDispatcherTest.php
> +use Prophecy\Argument;
phpunit provides prophecy through its `TestCase::prophesize()` method. That means it's mostly an implementation detail, and could only be removed in a major release, which requires changes to slim's composer.json to update. No unexpected build fails..
Anyway, because I'm explicitly using the namespace `Prophecy` here, I'm fine to include prophecy as require-dev dependency – still, this is not a classic transitive dependency issue, as phpunit provides prophecy as part of its API.

2019-02-23 08:32 UTC, bnf commented on Slim/MiddlewareDispatcher.php
> +    public function add($middleware): bool
yup, I agree and fill adapt.

2019-02-23 08:35 UTC, froschdesign commented on Slim/MiddlewareDispatcher.php
> +        foreach ($middlewares as $middleware) {
I found 4 constructors in 4.x branch here on Github! :stuck_out_tongue_closed_eyes:

2019-02-23 08:42 UTC, froschdesign commented on Slim/MiddlewareDispatcher.php
> +        foreach ($middlewares as $middleware) {
Regardless, it would be better to document these requirements in a coding standards. Otherwise, such things will appear again and again – in pull requests and reviews.

2019-02-23 08:49 UTC, l0gicgate commented on Slim/MiddlewareDispatcher.php
> +        foreach ($middlewares as $middleware) {
We have a discussion in #2502 about coding standards we’d like to implement. It’s in the works! You’re more than welcome to join the discussion!

2019-02-23 09:08 UTC, l0gicgate commented on tests/MiddlewareDispatcherTest.php
> +use Prophecy\Argument;
That was mainly my point, you’re explicitly using that namespace which means we should add it to our `composer.json` file regardless if PHPUnit uses/provides it or not.

On another note, if we’re going to use that style of testing (Prophesizing interfaces) then we should slowly migrate the entire test suite to do this so we maintain cohesiveness. 

Please add input on #2585 @bnf

2019-02-23 09:36 UTC, akrabat commented on Slim/MiddlewareDispatcher.php
> +                } elseif (is_subclass_of($this->middleware, MiddlewareInterface::class)) {
Currently, if the container factory returns a string that's the name of a class that implements `MiddlewareInterface`, then `4.x` will instantiate that class and use it. In this code, that no longer happens, I think?

2019-02-23 10:24 UTC, akrabat commented
A few quick benchmarks using siege indicates that this PR is 15% faster than the current `4.x`.

2019-02-23 16:20 UTC, l0gicgate commented on Slim/MiddlewareDispatcher.php
> +                } elseif (is_subclass_of($this->middleware, MiddlewareInterface::class)) {
That's correct @akrabat. If the container resolves to a class name and not an instantiated object then this will not instantiate the object as was being done in [DeferredResolutionMiddleware](https://github.com/slimphp/Slim/blob/4.x/Slim/Middleware/DeferredResolutionMiddleware.php#L64-L66)
```php
$container = new Container();
$container['myClass'] = MyMiddleware::class; // Not instantiated
```

As I said, the logic from `DeferredResolutionMiddleware` should be implemented.

2019-02-23 16:23 UTC, l0gicgate commented on Slim/Router.php
> +    public function handle(ServerRequestInterface $request): ResponseInterface
@bnf another thing, when you put that logic inside `Router` you're assuming that whoever implements that `RouterInterface` is going to copy that logic and if they don't then the expected behavior doesn't happen. As seen in `App::__construct()` you can provide your own `RouterInterface`. I really believe that logic doesn't belong here.

2019-02-25 20:12 UTC, bnf commented on Slim/MiddlewareDispatcher.php
> +        foreach ($middlewares as $middleware) {
To get this discussion resolved for this thread I've dropped this part from the constructor. It was mostly used for tests anyway, which means it's actually unneeded.

2019-02-25 20:13 UTC, bnf commented on Slim/Router.php
> +     * @var ContainerInterface
Yup, fixed.

2019-02-25 20:13 UTC, bnf commented on Slim/Router.php
> +    public function handle(ServerRequestInterface $request): ResponseInterface
Hm.. I understand that this seems strange. So let me name my argument: A router actually routes something, this is what it does with `handle` now. Previously the router was only a route-calculator, but not a router. To reflect this change I actually updated the `RouterInterface`.
To sum up: We have two operations: route calculation and route dispatch. That means one middleware and one dispatcher. I changed the `Router` to be a dispatcher now.
Maybe the naming is the problem here. We should probably put the route calculation logic directly into the `RoutingMiddleware` and then have a `RouteDispatcher` and no `Router` at all.

2019-02-25 20:13 UTC, bnf commented on tests/MiddlewareDispatcherTest.php
> +use Prophecy\Argument;
I've added the dependency to composer.json now.

2019-02-25 20:14 UTC, bnf commented on Slim/MiddlewareDispatcher.php
> +                } elseif (is_subclass_of($this->middleware, MiddlewareInterface::class)) {
You are right and I have no problem with implementing that (and did so for now), but well, may I ask: what is the usecase to return a `string` or a `Closure` from a DI container that needs to be instantiated manually with `new` then? If one actually adds something to a container, then a proper object implementing `MiddlewareInterface` should and can be easily used, no?
I'm really fine with keeping the current behaviour with this patch, but maybe this behaviour should be revisted within another patch?

2019-02-25 20:17 UTC, bnf commented on Slim/MiddlewareDispatcher.php
> +     * @var ContainerInterface
fixed.

2019-02-25 20:51 UTC, l0gicgate commented on Slim/MiddlewareDispatcher.php
> +                } elseif (is_subclass_of($this->middleware, MiddlewareInterface::class)) {
It's the same behavior as `CallableResolverInterface` as seen here https://github.com/slimphp/Slim/blob/4.x/Slim/CallableResolver.php#L73. 

This case only usually happen in the event that no container is present. So the instantiation of the object is deferred to when it gets resolved. It could happen with a container as well but very seldomly would a user intentionally do this.

Also see issue #2592 we need to pass container in there to duplicate the callable resolver behavior. I created that issue because someone who's doing testing on `4.x` said that they didn't understand why the same behavior from `CallableResolver` wasn't being replicated in `DeferredResolutionMiddleware` (passing the container to the instantiated object's constructor). [See original message from Slack Discussion](https://slimphp.slack.com/archives/C06SHUR19/p1551046761239000). That makes me thing this feature is being used.

2019-02-25 21:22 UTC, l0gicgate commented on Slim/Router.php
> +    public function handle(ServerRequestInterface $request): ResponseInterface
I think that we should separate the current `Router` into 2 interfaces. `RouteCollectorInterface` and `RouteDispatcher` interface.

The first interface will be `RouteCollectorInterface`:
```php
interface RouteCollectorInterface {
    public function map(array $methods, string $pattern, $handler): RouteInterface;

    public function pushGroup(string $pattern, $callable): RouteGroupInterface;

    public function popGroup();

    public function getNamedRoute(string $name): RouteInterface;

    public function lookupRoute(string $identifier): RouteInterface;

    public function relativePathFor(string $name, array $data = [], array $queryParams = []): string;

    public function pathFor(string $name, array $data = [], array $queryParams = []): string;

    public function setDefaultInvocationStrategy(InvocationStrategyInterface $strategy);
}
```

And a `RouteDispatcherInterface`:
```php
use Psr\Http\Server\RequestHandlerInterface;
use Slim\RoutingResults;

class RouteDispatcherInterface extends RequestHandlerInterface {
    public function dispatch(ServerRequestInterface $request): RoutingResults;

    public function setDispatcher(Dispatcher $dispatcher): RouteDispatcherInterface;
}
```

2019-02-26 09:56 UTC, akrabat commented on Slim/Router.php
> +    public function handle(ServerRequestInterface $request): ResponseInterface
There are three things that need to happen:

1. Registering route paths to handlers
2. Determination of the route handler to execute based on the request's URI
3. Executing the handler

These all need to be separate.

1. Registration happens before `run()`
2. Determination of the route handler to execute needs to occur in the middle of the middleware execution so that the user can register middleware before and after it happens.
3. Execution of the handler happens last

Within Symfony's Routing component, there is a `RouteCollection` object that you register route paths too. . Then `Router::matchRequest()` (which calls `UriMatcher::match()` is used to determine the controller to execute. The actual execution is done completely separately in the HttpKernel component, where `Kernel::handleRaw()` method instantiates a controller class (via an event) and then invokes it using `$controller(...$arguments)`

To circle back to Slim, we need to have these tasks separated too. I don't mind what we call them, but they must be separate. In Slim 3, you register your paths into the Router object and then use it to determine the handler to be  executed. This determination is very clunky in Slim 3's `App` and can only be at the start or end of the middleware chain. The actual dispatching is the application's job and is done in `App::__invoke()`. Due to the way Slim 3's middleware stack is set up, `App::__invoke` is _always_ the innermost middleware of the stack.  

In `4.x` today, `App` is no longer its own middleware and the dispatching is now in `DispatchMiddleware` which is much more explicit as now `DispatchMiddleware` is the innermost middleware. I agree with @bnf that  it should be a request handler, not a middleware though as we're never gonna call `handle`. 

 In `2591`, the Router does the dispatching too as it is a request handler in addition to a router though it doesn't explicitly implement `RequestHandlerInterface`. I'm not so much a fan of this as it makes the router do double duty. However, our Route objects are remarkably confused on this point too mind you.

2019-02-26 10:01 UTC, akrabat commented on Slim/MiddlewareDispatcher.php
> +                } elseif (is_subclass_of($this->middleware, MiddlewareInterface::class)) {
> what is the usecase to return a `string` or a `Closure` from a DI container that needs to be instantiated manually with `new` then? If one actually adds something to a container, then a proper object implementing `MiddlewareInterface` should and can be easily used, no?

This is a good question. I was mostly observing how it currently works rather than asking whether it should do this or not :)

Let's open an issue to consider it separately as this PR is already a bit too big…

2019-02-26 10:07 UTC, akrabat commented on Slim/MiddlewareDispatcher.php
> +        $this->tip = new class($middleware, $next) implements RequestHandlerInterface {
FWiW, I don't mind the anonymous functions as they are analogous to the closures we used in Slim 3. One advantage is that a user can't instantiate them, so they can never be part of Slim 4's public API and so have to be supported by us. One disadvantage is that they are opaque and not as explicit as a named class.

 I don't hold a strong opinion on this at all and can go either way.

2019-02-26 10:09 UTC, akrabat commented on Slim/MiddlewareDispatcher.php
> +    public function addLazy(string $middleware)
I also prefer the _deferred_ over _lazy_.

2019-02-28 17:51 UTC, l0gicgate commented on Slim/Router.php
> +    public function handle(ServerRequestInterface $request): ResponseInterface
@akrabat I agree.

App should be in charge of these concerns:
- Collecting routes using `RouteCollector`
- Then we should have `App` create a `RouteResolver` which takes in the `RouteCollector`, creates the `FastRoute\Dispatcher`.
- Then we need to remove `DispatchMiddleware` (`Router::handle()` in this PR) and simply run middleware signature detection in `App`. We can simply have the `App::addMiddleware()` method look to see if `RoutingMiddleware` has been added to the queue or not, if it hasn't been then we add it to `MiddlewareRunner` right before we call `$this->middlewareRunner->handle($request)` in `App`
- After the `MiddlewareRunner` finished its job `App` can run the appropriate route and return the response.

And voila. You now have gotten rid of all the problems and separated concerns properly, Let me fork this PR and show the changes I would apply.

2019-02-28 18:46 UTC, bnf commented on Slim/MiddlewareDispatcher.php
> +                } elseif (is_subclass_of($this->middleware, MiddlewareInterface::class)) {
Yup, fine by me.

2019-02-28 18:47 UTC, bnf commented on Slim/RouteGroup.php
> +    protected $middlewares = [];
No, it's `middlewares`. See https://en.wiktionary.org/wiki/middleware
> middleware (usually uncountable, plural **middlewares**)

2019-02-28 18:47 UTC, bnf commented on Slim/Route.php
> +        ContainerInterface $container = null,
`$invocationStrategy` actually is nullable, no need to refactor this one.

2019-02-28 18:48 UTC, bnf commented on Slim/MiddlewareDispatcher.php
> +            public function handle(ServerRequestInterface $request): ResponseInterface
I think that is out of scope for this patch, as @akrabat already said question regarding resolving should be handled in another issue.

2019-02-28 18:49 UTC, bnf commented on Slim/MiddlewareDispatcher.php
> +    public function addLazy(string $middleware)
Ok, fine by me. Changed that to be `addDeferred`.

2019-02-28 18:54 UTC, bnf commented on Slim/MiddlewareDispatcher.php
> +        $this->tip = new class($middleware, $next) implements RequestHandlerInterface {
That's exactly the reason why I thought anonymous classes would actually be the right choice here. There is really only one reason for using a class at all: We need to fullfill the `RequestHandlerInterface` requirement of PSR-15 middlewares. So the anonymous classes are just an implementation detail of the `MiddlewareDispatcher` here (and don't differ much from the Closure that we used in slim v3).
These classes are basicly closures (of course I do not refer `\Closure`s here, just the semantic meaning) that implement an interface, and the language construct to implement that is `new class`.

2019-02-28 18:54 UTC, bnf commented on Slim/Router.php
> +    public function handle(ServerRequestInterface $request): ResponseInterface
@akrabat ok, fine. I've moved the dispatch logic out of the `Router` again and moved it into a separate `RouteDispatcher` which implements `RequestHandlerInterface`.

No need to fork this pull request..

2019-02-28 20:36 UTC, l0gicgate commented on Slim/Router.php
> +    public function handle(ServerRequestInterface $request): ResponseInterface
@bnf @akrabat see https://github.com/l0gicgate/Slim/tree/4.x-SeparateRoutingConcerns

This was forked from @bnf's branch. I separated all the concerns accordingly. It's much cleaner and it makes sense.

@bnf, please diff against your branch.

2019-03-01 04:26 UTC, l0gicgate commented on Slim/MiddlewareDispatcher.php
> +        $this->tip = new class($middleware, $next) implements RequestHandlerInterface {
Those are good points @akrabat & @bnf. I can live with the internal class declaration, I'll just close my eyes xD

2019-03-01 14:39 UTC, l0gicgate commented on Slim/RouteGroup.php
> +    protected $middlewares = [];
@bnf we’re going to go with “middleware”. I don’t care about what wikipedia says. Just like we don’t say “softwares” or “hardwares”, the word “middleware” is uncountable as stated in the wiki you linked. You can leave it, I’ll just change it myself later.

2019-03-01 14:41 UTC, l0gicgate commented on Slim/MiddlewareDispatcher.php
> +            public function handle(ServerRequestInterface $request): ResponseInterface
Ok, I’ll PR it myself later. Don’t worry about it.

2019-03-01 15:41 UTC, bnf commented on Slim/MiddlewareDispatcher.php
> +            public function handle(ServerRequestInterface $request): ResponseInterface
No, sorry, I definitely overlooked that slim always used `middleware` as plural. I've updated my changes to reflect that.

2019-03-01 16:55 UTC, akrabat commented on Slim/Router.php
> +    public function handle(ServerRequestInterface $request): ResponseInterface
> I've moved the dispatch logic out of the `Router` again and moved it into a separate `RouteDispatcher` which implements `RequestHandlerInterface`.

Lovely, thanks! I can't see the commit where you did this though?

2019-03-01 18:06 UTC, l0gicgate commented on tests/MiddlewareDispatcherTest.php
> +    public function testDoesNotInstantiateLazyMiddlewareInCaseOfAnEarlyReturningOuterMiddleware()
**Should use the keyword "Deferred" instead of "Lazy":**
`public function testDoesNotInstantiateDeferredMiddlewareInCaseOfAnEarlyReturningOuterMiddleware()`

2019-03-01 18:06 UTC, l0gicgate commented on tests/MiddlewareDispatcherTest.php
> +    public function testThrowsExceptionForLazyNonMiddlewareInterfaceClasses()
**Should use the keyword "Deferred" instead of "Lazy":**
`public function testThrowsExceptionForDeferredNonMiddlewareInterfaceClasses()`

2019-03-01 19:25 UTC, l0gicgate commented
Please add test coverage on:
https://coveralls.io/builds/21930483/source?filename=Slim%2FApp.php#L112
https://coveralls.io/builds/21930483/source?filename=Slim%2FRoute.php#L292
https://coveralls.io/builds/21930483/source?filename=Slim%2FRouteGroup.php#L69

2019-03-02 10:54 UTC, akrabat approved these changes

2019-03-02 11:02 UTC, merged