4.x Refactor AppTest To Use Prophecy
slimphp/Slim pull request #2603
Opened 2019-03-03 21:20 UTC by l0gicgate

This is a continuation of migrating towards the usage of `phpspec/prophecy`.

@bnf and @akrabat please review!

2019-03-03 22:20 UTC, bnf reviewed
Nice change, I have some comments, and will send them as pull request to your branch next to the review in here.

2019-03-03 22:20 UTC, bnf commented on tests/AppTest.php
> +        $handlerMock = $this->getMockBuilder('MockRouteHandler')
Hm.. I know we had our debate about anonymous classes, but I personally quite dislike `MockBuilder::setMethods` for its different semantics (of course that call to `setMethods` is required here, because we are mocking an non existent class/method, i don't doubt that). Also mocking a non existent class is a bit of a hack (I know it was the same before, when using `stdClass`).

Would you mind to use an anonymous class here?

2019-03-03 22:20 UTC, bnf commented on tests/AppTest.php
> +        $containerProphecy->has(Argument::exact('handler'))->willReturn(true);
`Argument::exact` is implicit when defining non `\Prophecy\Argument` arguments, so that ` $containerProphecy->has('handler')->willReturn(true);` would be the same, but shorter.
The `phpspec/prophecy` uses the latter in its documentation.
I think it would be good, when we use one of these consistently.
I don't have a strong opinion on this, but I'd go with what is easier to type and what the documentation suggests.

2019-03-03 22:20 UTC, bnf commented on tests/AppTest.php
> +            $hasBeenRead = true;
As we can mutate state in a promise this should do sth like the following instead of modified a bound boolean:
```php
$this->eof()->willReturn(true);
```

2019-03-03 22:20 UTC, bnf commented on tests/AppTest.php
> +            $streamBody .= $args[0];
We should try to mutate state here. Something like:
```php
$body = $this->reveal()->getBody();
$this->getBody()->willReturn($body . $args[0]);
```
Will send a PR.

2019-03-03 22:24 UTC, l0gicgate commented on tests/AppTest.php
> +        $handlerMock = $this->getMockBuilder('MockRouteHandler')
I have no problems doing that. I've actually come around on the anonymous class issue, it just really triggers my OCD but that's my own problem. I will refactor to use an anonymous class! Thanks

2019-03-03 22:25 UTC, l0gicgate commented on tests/AppTest.php
> +        $containerProphecy->has(Argument::exact('handler'))->willReturn(true);
Oh okay, gotcha. I'm new to using Prophecy, I will change the usage of `Argument::exact()` to just the string. Let's go with the easier to type version!

2019-03-03 22:26 UTC, l0gicgate commented on tests/AppTest.php
> +            $hasBeenRead = true;
Haha I didn't think of that! I will change it. That's great!

2019-03-03 22:27 UTC, l0gicgate commented on tests/AppTest.php
> +            $streamBody .= $args[0];
Yeah for sure, that would be much cleaner. I will refactor to do that instead.

2019-03-03 22:45 UTC, l0gicgate commented
@bnf please re-review. Just fixed all the requested changes!

2019-03-08 22:14 UTC, bnf requested changes
Thanks, looks good. I have some minor comments, but generally this is good to go for me.
As already discussed on slack, I like that we actually test public facing code, instead of implementation details now (which will be actually the case once we remove the two remaining property reflections, as per my comments)

2019-03-08 22:14 UTC, bnf commented on tests/AppTest.php
> +        foreach ($methods as $method) {
This could (maybe even should) use the `upperCaseRequestMethodsProvider` that you introduced for `testGetPostPutPatchDeleteOptionsMethods`.

Someone once told me that tests shouldn't use loops. It made sense to me, therefore I'd avoid them here as well.

2019-03-08 22:14 UTC, bnf commented on tests/AppTest.php
> +        $app->map([$method], '/', function ($request, ResponseInterface $response) {
Would be nice to add a type declaration for `$request` as well.

2019-03-08 22:14 UTC, bnf commented on tests/AppTest.php
> +     * @dataProvider  routePatternsProvider
double space

2019-03-08 22:14 UTC, bnf commented on tests/AppTest.php
> +            [['', ''], ''], // testEmptyGroupWithEmptyRoute
We could use named data provider entries which allow to use phpunit `--filter` flag in case one needs to debug the tests e.g.:
```
['empty group with segment route that does not end in a slash' => [
    '', '/foo'], '/foo'
],
```
You could automatically convert your current format using some substitutions (vi here):
```
:'<,'>s/\[\(.*\)\], \/\/ test\(.*\)$/'\2' => [^M                \1^M            ],/
:'<,'>s/\([^']\)\([A-Z]\)/\1 \l\2/g
:'<,'>s/'\([A-Z]\)/'\l\1/g
```

2019-03-08 22:14 UTC, bnf commented on tests/AppTest.php
> +        $this->assertEquals($pattern, $patternProperty->getValue($route));
`Slim\Routable` has a `getPattern()` method, that means the Reflection is not needed here. :)
This may just be: `$this->assertEquals($pattern, $route->getPattern());`

2019-03-08 22:14 UTC, bnf commented on tests/AppTest.php
> +        $this->assertEquals($expectedPath, $patternProperty->getValue($route));
Same as before, `Slim\Routable` has a `getPattern()` method.
This may just be: `$this->assertEquals($expectedPath, $route->getPattern());`

2019-03-08 22:14 UTC, bnf commented on tests/AppTest.php
> +            $called++;
Would be nice to use the prophecy method `shouldBeCalled` (or even `shouldHaveBeenCalled`) instead.

2019-03-08 22:14 UTC, bnf commented on tests/AppTest.php
> +            $called++;
Would be nice to use the prophecy method `shouldBeCalled` (or even `shouldHaveBeenCalled`) instead.

2019-03-08 22:14 UTC, bnf commented on tests/AppTest.php
> -
Missing spaces between `name`, `=>` and `foo`.

2019-03-08 22:14 UTC, bnf commented on tests/AppTest.php
> -
Why do you remove the `ServerRequestInterface` type declaration here (also in following test methods)?

2019-03-08 22:14 UTC, bnf commented on tests/AppTest.php
> -
Would be nice to use `shouldBeCalled` (or `shouldHaveBeenCalled`) instead.

2019-03-10 17:44 UTC, l0gicgate commented on tests/AppTest.php
> +     * @dataProvider  routePatternsProvider
fixed

2019-03-10 17:44 UTC, l0gicgate commented on tests/AppTest.php
> +            $called++;
done. refactored to use `shouldHaveBeenCalled()`

2019-03-10 17:45 UTC, l0gicgate commented on tests/AppTest.php
> -
fixed

2019-03-10 21:14 UTC, akrabat approved these changes

2019-03-10 21:44 UTC, merged