Add type check for $headers
slimphp/Slim pull request #2633
Opened 2019-04-17 12:28 UTC by adriansuter

As $headers may not be an array, we added an if statement to avoid any warnings. 
See #2632

2019-04-17 14:57 UTC, l0gicgate requested changes

2019-04-17 14:57 UTC, l0gicgate commented on Slim/Http/Headers.php
>          if (empty($authorization) && is_callable('getallheaders')) {
It feels like a lot of nested statements. Would this be cleaner?
```php
if (
    empty($authorization) 
    && is_callable('getallheaders') 
    && $headers = getallheaders()
) {
    $headers = array_change_key_case($headers, CASE_LOWER);
    if (isset($headers['authorization'])) {
        $environment->set('HTTP_AUTHORIZATION', $headers['authorization']);
    }
}
```

2019-04-17 15:06 UTC, adriansuter commented on Slim/Http/Headers.php
>          if (empty($authorization) && is_callable('getallheaders')) {
Sure.

2019-04-17 15:44 UTC, akrabat requested changes

2019-04-17 15:44 UTC, akrabat commented on Slim/Http/Headers.php
> +        if (empty($authorization) && is_callable('getallheaders') && $headers = getallheaders()) {
I know you've just changed this, but it was better before.

Assigning to a variable inside of an `if` statement is difficult for long term maintenance as it looks like it should be an `==` test.

2019-04-17 15:55 UTC, adriansuter commented on Slim/Http/Headers.php
> +        if (empty($authorization) && is_callable('getallheaders') && $headers = getallheaders()) {
True. How about early returns? I mean
```php
        if (!empty($authorization)) {
                return $environment;
        }
        if (!is_callable('getallheaders')) {
                return $environment;
        }
        $headers = getallheaders();
        if (!is_array($headers)) {
            return $environment;
        }

        $headers = array_change_key_case($headers, CASE_LOWER);
        if (isset($headers['authorization'])) {
            $environment->set('HTTP_AUTHORIZATION', $headers['authorization']);
        }

        return $environment;
```

2019-04-17 16:06 UTC, akrabat commented on Slim/Http/Headers.php
> +        if (empty($authorization) && is_callable('getallheaders') && $headers = getallheaders()) {
Works for me. Personally, I'd combine the first two `if` statements:

```php
if (!empty($authorization) || !is_callable('getallheaders')) {
```

Also, add a blank line between after each `}`

2019-04-17 16:10 UTC, l0gicgate commented on Slim/Http/Headers.php
> +        if (empty($authorization) && is_callable('getallheaders') && $headers = getallheaders()) {
Sorry for suggestion a variable declaration in a condition. Here's my suggestion
```php
public static function determineAuthorization(Environment $environment)
{
    $authorization = $environment->get('HTTP_AUTHORIZATION');

    if (!empty($authorization) || !is_callable('getallheaders')) {
        return $environment;
    }

    $headers = getallheaders();
    if (is_array($headers)) {
        $headers = array_change_key_case($headers, CASE_LOWER);
        if (isset($headers['authorization'])) {
            $environment->set('HTTP_AUTHORIZATION', $headers['authorization']);
        }
    }

    return $environment;
}
```

2019-04-17 20:45 UTC, l0gicgate approved these changes

2019-04-17 20:49 UTC, l0gicgate commented on Slim/Http/Headers.php
> +        if (!is_array($headers)) {
Can I get you to write a test for this if statement please?

2019-04-18 16:36 UTC, adriansuter commented on Slim/Http/Headers.php
> +        if (!is_array($headers)) {
Of course, I will give it a try.

So I need to override the built-in function `getallheaders()`. In one test the function would return false, in another test, the function would return an array. So far so good. Do you use any library to mock/override the built-in functions? I haven't found one in your source code.

All I could see is the php-file `PhpFunctionOverrides.php` in `tests/Assets`. So I suppose you use the namespace method to override the built-in php functions. That is fine. Well, the namespace of course for the class is `Slim\Http`. So in order to override the `getallheaders()` method, I need to create a new file for this namespace, needn't I?

Do you know for example [the method to be able to control the behaviour of the overriden function depending on the calling method](http://www.manuel-strehl.de/dev/overwrite_PHP_built-in_functions.en.html)? Would it make sense to implement such a helper `_mock()` function for unit testing? It has a GPL and a MIT license.

2019-04-18 17:50 UTC, l0gicgate commented on Slim/Http/Headers.php
> +        if (!is_array($headers)) {
So this is a bit complex I suppose. You do need to override `getallheaders()` but since it is used in the namespace `Slim\Http` you'll need to create a new function override file in `tests\Assets` called `PhpHttpFunctionOverrides.php` and put the contents:

```php
<?php
/**
 * Slim Framework (https://slimframework.com)
 *
 * @link      https://github.com/slimphp/Slim
 * @copyright Copyright (c) 2011-2017 Josh Lockhart
 * @license   https://github.com/slimphp/Slim/blob/3.x/LICENSE.md (MIT License)
 */

namespace Slim\Http;

function getallheaders()
{
    return GETALLHEADERS_RETURN;
}

```

Then in `composer.json` you'll need to add `PhpHttpFunctionOverrides.php` to the `files` property:
```json
"autoload-dev": {
    "files": [
        "tests/Assets/PhpFunctionOverrides.php",
        "tests/Assets/PhpHttpFunctionOverrides.php"
    ]
},
```

Make sure that you do `composer dumpautoload` after you make that change so the override is loaded on your end. Once that's done you can write your tests. In the tests you'll have to define the constant like so:

```php
public function testDetermineAuthorizationReturnsEarlyIfHeadersIsNotArray()
{
    // Define it as false, or ['existing' => 'header']
    define('GETALLHEADERS_RETURN', false);

    ...your assertions...
}
```

Hope this helps!

2019-04-23 08:44 UTC, adriansuter commented on Slim/Http/Headers.php
> +        if (!is_array($headers)) {
The test is implemented. I used $GLOBALS in order to be able to set the return value to `false` only for this test. Otherwise it may affect other tests executed afterwards. Is that okay?

2019-04-23 12:25 UTC, adriansuter commented on Slim/Http/Headers.php
> +        if (!is_array($headers)) {
To avoid `$GLOBALS` we could also override the function like this
```php
// tests/Assets/PhpHttpFunctionOverrides.php
function getallheaders()
{
    $backtrace = debug_backtrace();
    foreach ($backtrace as $step) {
        if ($step['function'] === 'testDetermineAuthorizationReturnsEarlyIfHeadersIsNotArray') {
            return false;
        }
    }

    return \getallheaders();
}
```
So the function would check the backtrace, whether a caller has the name of the test.

**Problem: When the name of the method gets changed, the test would not work anymore.**

What do you think?

2019-04-23 17:09 UTC, l0gicgate commented on Slim/Http/Headers.php
> +        if (!is_array($headers)) {
This is why I'd rather define a constant which explicitly shows in the test what the return value will be. Also `getallheaders()` isn't being used anywhere else in the codebase.

**The override could be:**
```php
function getallheaders()
{
    return defined('GETALLHEADERS_RETURN') ? GETALLHEADERS_RETURN : \getallheaders();
}
```

2019-04-23 21:15 UTC, merged