3.x codecov
slimphp/Slim pull request #2701
Opened 2019-05-30 00:54 UTC by hopeseekr

Unfortunately for me, I only saw the stupid 4.x branch when I was preparing the fork.

You **really** ought to do all new development on the `master` branch :-(

2019-05-30 01:02 UTC, carc1n0gen commented
That's simply not how this project does things.  There actually is no master branch at all.

2019-05-30 03:57 UTC, l0gicgate requested changes
I don't particularly see the purpose of this PR. I'm uneasy about removing things from the `App` core when we're this deep in the release cycle with no actual value added.

2019-05-30 03:57 UTC, l0gicgate commented on Slim/App.php
>          try {
This try/catch block should be removed altogether since it's not catching anything.

2019-05-30 03:57 UTC, l0gicgate commented on Slim/App.php
> +    public function respond(ResponseInterface $response, $connectionStatus = 'connection_status')
Why are you adding this to the function's signature? Instead you should stub the `connection_status` function to achieve this.

2019-05-30 12:55 UTC, hopeseekr commented on Slim/App.php
> +    public function respond(ResponseInterface $response, $connectionStatus = 'connection_status')
Do you know how it is possible to override global functions like `connection_status()` ? I am pretty sure it is not possible except via the Runkit terrible hack.

2019-05-30 13:28 UTC, JoeBengalen commented on Slim/App.php
> +    public function respond(ResponseInterface $response, $connectionStatus = 'connection_status')
In the 4.x branch it is done like this:
https://github.com/slimphp/Slim/blob/4.x/tests/Assets/PhpFunctionOverrides.php

The trick is that namespace scoped functions takes precedence over global scoped functions.

2019-05-30 16:26 UTC, l0gicgate commented on Slim/App.php
> +    public function respond(ResponseInterface $response, $connectionStatus = 'connection_status')
The overrides for this namespace are located here https://github.com/slimphp/Slim/blob/3.x/tests/Assets/PhpFunctionOverrides.php

2019-05-30 22:43 UTC, hopeseekr commented on Slim/App.php
> +    public function respond(ResponseInterface $response, $connectionStatus = 'connection_status')
Thank you so much for teaching me this!

2019-05-30 22:43 UTC, hopeseekr commented on Slim/App.php
> +    public function respond(ResponseInterface $response, $connectionStatus = 'connection_status')
I have refactored it per your guidance. Thank you again.

2019-05-30 22:45 UTC, hopeseekr commented on Slim/App.php
>          try {
https://stackoverflow.com/questions/2614473/does-it-make-sense-to-do-try-finally-without-catch

I think in this context, it's possibly best to leave it.

2019-05-31 15:11 UTC, l0gicgate commented on tests/Assets/PhpFunctionOverrides.php
> +function connection_status($toggleFailure = false)
Let's use globals instead of changing the function signature.

2019-06-02 19:05 UTC, l0gicgate commented on tests/Assets/PhpFunctionOverrides.php
> +function connection_status()
Please add docblock for this.

2019-06-03 03:25 UTC, hopeseekr commented on tests/Assets/PhpFunctionOverrides.php
> +function connection_status($toggleFailure = false)
Done.

2019-06-03 03:25 UTC, hopeseekr commented on tests/Assets/PhpFunctionOverrides.php
> +function connection_status()
Done.

2019-06-03 18:55 UTC, l0gicgate commented on Slim/App.php
>          try {
Please remove this try/finally block. To me it doesn't add any value here, it was originally there to catch an exception.

2019-06-18 17:59 UTC, l0gicgate commented
@hopeseekr it's been two weeks that I've requested for the changes are you going to proceed with this? If not, I'm going to close this PR.

Thanks

2019-07-22 19:43 UTC, l0gicgate commented
I'm closing this PR as stale since @hopeseekr is not responding.

2019-07-22 19:43 UTC, closed without merging