Added 100% code coverage. Hurray!!
slimphp/Slim pull request #2702
Opened 2019-05-30 23:32 UTC by hopeseekr

Based off of my work in PR #2701.

2019-05-31 10:24 UTC, adriansuter commented
And the work of many others 😉

2019-05-31 15:09 UTC, l0gicgate requested changes

2019-05-31 15:09 UTC, l0gicgate commented on tests/Assets/PhpRoutingFunctionOverrides.php
> +namespace Slim
Can you adopt the same pattern that is being adopted with the other overrides instead of including two namespaces in one file. Use globals to override the return value.

2019-06-01 10:54 UTC, hopeseekr commented on tests/Assets/PhpRoutingFunctionOverrides.php
> +namespace Slim
Thank you @l0gicgate  so much for teaching me something new and valuable!! I really appreciate it!

2019-06-02 19:05 UTC, l0gicgate commented on tests/Assets/PhpFunctionOverrides.php
> +function connection_status()
Please add docblock for this function

2019-06-03 03:24 UTC, hopeseekr commented on tests/Assets/PhpFunctionOverrides.php
> +function connection_status()
Done.

2019-06-03 18:51 UTC, l0gicgate approved these changes

2019-06-03 18:51 UTC, merged