[WIP] 4.x - Add an advanced callable resolver
slimphp/Slim pull request #2787
Opened 2019-08-09 13:01 UTC by adriansuter

This PR addresses #2780.

It defines a new `AdvancedCallableResolver` and a corresponding interface which extends the existing `CallableResolverInterface`. The advanced callable resolver would be created by default in the `App` constructor (if none had been passed).

The `MiddlewareDispatcher` would get the callable resolver as third optional param (non-BD). If it has one, and if the resolver is advanced, then the dispatcher would call the `resolveMiddleware` method. If the resolver is not advanced or if there is not even a resolver available, the dispatcher would execute its own hard coded resolving.

The `\Slim\Routing\Route` and the `\Slim\Routing\RouteGroup` would check if the resolver is advanced. If so, they call `resolveRoute` to perform the resolving. Otherwise they do as before.

Note: All the test cases for the callable resolver had been copied and implemented for the advanced callable resolver. Some of them were "triplicated", because two had to throw exceptions and one not.

2019-08-09 18:54 UTC, l0gicgate requested changes
@adriansuter that's a really good solution so we entirely avoid any BC breaks. It's also opt-in for developers to implement which is awesome. Great work

2019-08-09 18:54 UTC, l0gicgate commented on Slim/MiddlewareDispatcher.php
> +        ?CallableResolverInterface $callableResolver = null
I think that we should make this parameter non-optional.

2019-08-09 18:54 UTC, l0gicgate commented on Slim/MiddlewareDispatcher.php
> +                } elseif ($this->callableResolver instanceof AdvancedCallableResolverInterface) {
This should be pushed to the top of this function, we should always prioritize the `AdvancedCallableResolver` to resolve first and fallback on the other logic if it's not present.

2019-08-09 18:54 UTC, l0gicgate commented on Slim/AdvancedCallableResolver.php
> +    private function checkResolvedAndBindContainerIfClosure($resolved, $toResolve): callable
let's change this method name to
```php
private function assertCallableAndBindClosureToContainer($resolved, $toResolve): callable
```

2019-08-10 09:19 UTC, adriansuter commented on Slim/AdvancedCallableResolver.php
> +    private function checkResolvedAndBindContainerIfClosure($resolved, $toResolve): callable
Sure.

2019-08-10 09:19 UTC, adriansuter commented on Slim/MiddlewareDispatcher.php
> +        ?CallableResolverInterface $callableResolver = null
Wouldn't that be a BC?

2019-08-10 09:25 UTC, adriansuter commented on Slim/MiddlewareDispatcher.php
> +                } elseif ($this->callableResolver instanceof AdvancedCallableResolverInterface) {
Agree. Currently, if the callable resolver is given but not an advanced one, then this whole `handle()` method would always throw an exception. Do you think we should, in case the callable resolver is non-advanced, process the hard-coded resolving instead of just throwing the exception?

2019-08-10 15:28 UTC, l0gicgate commented on Slim/MiddlewareDispatcher.php
> +        ?CallableResolverInterface $callableResolver = null
Nope since currently the MiddlewareDispatcher was instantiated internally and not accessible to the end user.

2019-08-10 15:39 UTC, l0gicgate commented on Slim/MiddlewareDispatcher.php
> +                } elseif ($this->callableResolver instanceof AdvancedCallableResolverInterface) {
In the case that a non-advanced one is passed that would mean it’s a custom one which means it’s up to them to resolve these objects how they want to. The whole point of this change is to force the dispatcher to use `CallableResolver`. 

What we could do is in case of a non advanced resolver we wrap the `resolve` method in a try catch and fall back on that resolution logic in case that it can’t resolve it. What do you think?

2019-08-10 17:43 UTC, adriansuter commented on Slim/MiddlewareDispatcher.php
> +        ?CallableResolverInterface $callableResolver = null
So we need to change the whole signature of the constructor? Into something like
```php
    public function __construct(
        RequestHandlerInterface $kernel,
        CallableResolverInterface $callableResolver,
        ?ContainerInterface $container = null
    ) {
```
Are you sure about that? We will have to change a lot of test cases (as they obviously don't pass a callable resolver so far).

2019-08-10 18:18 UTC, l0gicgate commented on Slim/MiddlewareDispatcher.php
> +        ?CallableResolverInterface $callableResolver = null
Oh it will break a lot of internals for sure. No external BCs though.

2019-08-10 23:15 UTC, adriansuter commented
Okay, there are a lot of changes in the unit tests. I tried to make sure that they test the non-advanced callable resolver as well as the advanced callable resolver.

Two tests did not work as expected. But only if the callable resolver was non-advanced:
* `\Slim\Tests\MiddlewareDispatcherTest::testDeferredResolvedClosureIsBoundToContainer`
* `\Slim\Tests\MiddlewareDispatcherTest::testFetchesMiddlewareFromContainer`

Any idea why? I think there is something wrong in the `\Slim\MiddlewareDispatcher::addDeferred() -> class::handle()` method. Just couldn't find the bug.

2019-08-11 19:06 UTC, adriansuter commented
@l0gicgate Merged your PR. Slim is now using the `\Slim\Interfaces\AdvancedCallableResolverInterface` for the `\Slim\CallableResolver` by default.

2019-08-11 21:25 UTC, l0gicgate approved these changes

2019-08-11 21:26 UTC, merged