Configure the application via a container
slimphp/Slim pull request #2793
Opened 2019-08-10 19:39 UTC by mnapoli

This is an implementation for what we discussed in #2778.

The idea is to simplify how to configure the application when using a PSR-11 container.

Here is an example with PHP-DI, using the default services from Slim:

```php
$container = new DI\Container;

$app = AppFactory::createFromContainer($container);
```

Here is an example when we want to overload one service:

```php
$container = new DI\Container;
$container->set(CallableResolverInterface::class, $customInstance);

$app = AppFactory::createFromContainer($container);
```

instead of the existing alternative:

```php
$container = new DI\Container;

AppFactory::setContainer($container);
AppFactory::setCallableResolver($customResolver);
$app = AppFactory::create($container);
```

The advantages:

- `AppFactory` is no longer affect by global state, meaning subsequent calls to `AppFactory::create()` will not be affected
- containers can come pre-configured for Slim

The 2nd point is interesting for PHP-DI: the bridge could provide a pre-configured container for Slim. Users would just have to call `AppFactory::createFromContainer($container)`, which is pretty cool.

2019-08-10 20:19 UTC, l0gicgate requested changes
This is great, thank you for this contribution. I would like to mention that I’d like to work closely with third-party library devs like you to make Slim flexible and sensical in terms of approaching different problems. I highly value your input @mnapoli

2019-08-10 20:19 UTC, l0gicgate commented on tests/Factory/AppFactoryTest.php
> +    public function testCreateAppWithContainerThatProvidesAllImplementations()
Just to keep the test suite cohesive can you use prophecies instead of mocks please? This also removes the need for a `MockContainer`

2019-08-10 20:19 UTC, l0gicgate commented on tests/Mocks/MockContainer.php
> +class MockContainer implements ContainerInterface
As mentioned in my comment above. There is no need for this mock class. Please use prophecies.

2019-08-10 20:39 UTC, mnapoli commented on tests/Factory/AppFactoryTest.php
> +    public function testCreateAppWithContainerThatProvidesAllImplementations()
👍 	roger on the prophecy mocks. However the MockContainer class makes everything simpler, the test will be much more complex and brittle here. Here we have an interface let's take advantage from it? :)

2019-08-10 20:45 UTC, mnapoli commented on tests/Factory/AppFactoryTest.php
> +    public function testCreateAppWithContainerThatProvidesAllImplementations()
![Capture d’écran 2019-08-10 à 22 44 08](https://user-images.githubusercontent.com/720328/62826711-625eb680-bbc0-11e9-9ac2-2c70fde0ab6c.png)

I'm giving it a try, I got no autocompletion because of prophecy's magic. I don't know these mocks. Do you have any pointer on how to make it return the correct object corresponding to the service name that is passed to `get()`?

2019-08-11 18:22 UTC, l0gicgate approved these changes

2019-08-11 18:23 UTC, l0gicgate commented
Looks good to me. Please have a quick look before I merge @adriansuter!

2019-08-11 19:25 UTC, adriansuter approved these changes

2019-08-11 19:26 UTC, adriansuter commented
@l0gicgate Can be merged.

We need to make sure that this possibility gets its way into the documentation.

2019-08-11 20:51 UTC, l0gicgate commented
@adriansuter 

> We need to make sure that this possibility gets its way into the documentation.

See https://github.com/slimphp/Slim-Website/issues/411

2019-08-11 20:52 UTC, merged