Add BodyParsingMiddleware
slimphp/Slim pull request #2798
Opened 2019-08-13 09:51 UTC by akrabat

This middleware will parse the body of a PSR-7 ServerRequest and if the content-type is known and a parser is registered, it will add the parsed data to the request object before passing to the next middleware. 

Usage:

```php
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Slim\Factory\AppFactory;
use Slim\Middleware\BodyParsingMiddleware;
use Slim\Psr7\Response;

$app = AppFactory::create();
$app->add(new BodyParsingMiddleware());

$app->post, '/foo', function (ServerRequestInterface $request): ResponseInterface {
    $data = $request->getParsedBody();

    $response = new Response();
    $response->getBody()->write(
        print_r($data, true)
    );
    return new Response();
});

$app->run();
```

2019-08-13 10:05 UTC, akrabat commented
Rebased to tip of `4.x` branch

2019-08-13 12:09 UTC, adriansuter requested changes
Good work. Some minor change requests.

2019-08-13 12:09 UTC, adriansuter commented on Slim/Middleware/BodyParsingMiddleware.php
> +use RuntimeException;
If the use statements should be in alphabetical order, then `RuntimeException` should be the last one.

2019-08-13 12:09 UTC, adriansuter commented on Slim/Middleware/BodyParsingMiddleware.php
> +     * @param array $bodyParsers list of body parsers as an associative array of mediaType => callable
As the array consists of `callable` elements only, we could actually type-hint the param as `callable[]`. The same holds for the `$bodyParsers` property.

2019-08-13 12:09 UTC, adriansuter commented on Slim/Middleware/BodyParsingMiddleware.php
> +     * Retreive media type parser.
Typo "Retrieve"?

2019-08-13 12:09 UTC, adriansuter commented on Slim/Middleware/BodyParsingMiddleware.php
> +    protected function registerDefaultBodyParsers()
We should type-hint the return.
```php
protected function registerDefaultBodyParsers(): void
```

2019-08-13 12:09 UTC, adriansuter commented on Slim/Middleware/BodyParsingMiddleware.php
> +            $result = simplexml_load_string($input);
If we are using these functions we should add the following lines to `composer.json` in the `require` section:
```json
        "ext-libxml": "*",
        "ext-simplexml": "*"
```

Then `ext-simplexml` can be removed from the `require-dev` section.

2019-08-13 12:09 UTC, adriansuter commented on Slim/Middleware/BodyParsingMiddleware.php
> +        $this->registerBodyParser('text/xml', function ($input) {
As the callables for `application/xml` and `text/xml` are doing the same thing, we could simplify
```php
        $xmlCallable = function ($input) {
            $backup = libxml_disable_entity_loader(true);
            $backup_errors = libxml_use_internal_errors(true);
            $result = simplexml_load_string($input);

            libxml_disable_entity_loader($backup);
            libxml_clear_errors();
            libxml_use_internal_errors($backup_errors);

            if ($result === false) {
                return null;
            }

            return $result;
        };

        $this->registerBodyParser('application/xml', $xmlCallable);

        $this->registerBodyParser('text/xml', $xmlCallable);
```

2019-08-13 12:09 UTC, adriansuter commented on Slim/Middleware/BodyParsingMiddleware.php
> +     * Note: This method is not part of the PSR-7 standard.
Does this "Note" make any sense here?

2019-08-13 12:09 UTC, adriansuter commented on tests/Middleware/BodyParsingMiddlewareTest.php
> +    public function testSettingAndGetttingAParser()
Typo? Getting has tripple `t`.

2019-08-13 13:02 UTC, akrabat commented on Slim/Middleware/BodyParsingMiddleware.php
> +            $result = simplexml_load_string($input);
I'm not sure about this. `BodyParsingMiddleware` is optional and if not used, then you don't need the xml extensions to run Slim.

2019-08-13 13:05 UTC, akrabat commented on Slim/Middleware/BodyParsingMiddleware.php
> +     * Note: This method is not part of the PSR-7 standard.
No - copy/paste error from Slim-Http :)

2019-08-13 13:09 UTC, froschdesign commented on Slim/Middleware/BodyParsingMiddleware.php
> +            $result = simplexml_load_string($input);
If a package or extension is not strictly required then use the `suggest` section: https://getcomposer.org/doc/04-schema.md#suggest

2019-08-13 13:17 UTC, akrabat commented on Slim/Middleware/BodyParsingMiddleware.php
> +            $result = simplexml_load_string($input);
Added to the `suggest` section.

2019-08-13 13:18 UTC, akrabat commented
@adriansuter Review items addressed.

2019-08-13 14:05 UTC, adriansuter approved these changes
Wonderful.

2019-08-13 15:35 UTC, l0gicgate requested changes
Minor changes. Mainly just doc bloc stuff. This is a great addition to our middleware suite.

2019-08-13 15:35 UTC, l0gicgate commented on Slim/Middleware/BodyParsingMiddleware.php
> +            throw new RuntimeException('No parser for type ' . $mediaType);
Can you add `@throws RuntimeException` to the doc bloc

2019-08-13 15:35 UTC, l0gicgate commented on Slim/Middleware/BodyParsingMiddleware.php
> +     * Register media type parser.
Let's remove this comment. The method name speaks for itself.

2019-08-13 15:35 UTC, l0gicgate commented on Slim/Middleware/BodyParsingMiddleware.php
> +     * Is a body parser registered for this media type?
Same here. The method name speaks for itself.

2019-08-13 15:35 UTC, l0gicgate commented on Slim/Middleware/BodyParsingMiddleware.php
> +     * Retrieve media type parser.
And same here. The method name speaks for itself.

2019-08-13 15:35 UTC, l0gicgate commented on Slim/Middleware/BodyParsingMiddleware.php
> +     * Register the default body parsers
Let's remove this comment as well.

2019-08-13 15:35 UTC, l0gicgate commented on Slim/Middleware/BodyParsingMiddleware.php
> +     * Get the request's media type, if known.
Remove this comment.

2019-08-13 15:35 UTC, l0gicgate commented on tests/Middleware/BodyParsingMiddlewareTest.php
> +     * Helper function to create a ServerRequest with a body and a content-type header
Let's remove this comment

2019-08-13 15:35 UTC, l0gicgate commented on Slim/Middleware/BodyParsingMiddleware.php
> +     * Constructor.
Can we remove this from the doc bloc, it's implied that it's the constructor. I want to keep comments cohesive throughout the code base. Only comments that are absolutely necessary should be present, which in most cases they are not if your code is explicit.

2019-08-13 15:54 UTC, akrabat commented
@l0gicgate Review items addressed.

2019-08-13 16:00 UTC, shadowhand commented
@akrabat what about adding `App::addBodyParsers(array $parsers = [])` like we have for error handling, etc.

2019-08-13 16:07 UTC, akrabat commented
> @akrabat what about adding `App::addBodyParsers(array $parsers = [])` like we have for error handling, etc.

A key reason that `addErrorMiddleware()` exists is that there's a number of dependencies to the constructor that the app instance can fill in for you.

That's not the case for this one, so we'd be adding it for the dev experience of:

```php
$app->addErrorMiddleware(true, true, true);
$app->addBodyParsing();
```

looking nicer than:

```php
$app->addErrorMiddleware(true, true, true);
$app->add(new Slim\Middleware\BodyParsingMiddleware());
```

I'm easy either way and defer to @l0gicgate on it.

2019-08-13 16:10 UTC, shadowhand commented
Before this is merged, I would like to give a more complete review of it. I think it can be improved and be made more friendly to IoC.

2019-08-13 16:50 UTC, anfly0 commented on Slim/Middleware/BodyParsingMiddleware.php
> +            $body = (string)$request->getBody();
What if the stream is not seekable (rewindable)?
This would be a problem if any subsequent middleware, for whatever reason, needed to access the raw body.
An example would be authentication via HMAC.

One solution would be to simply copy the non-seekable stream to a new seekable stream.

2019-08-13 19:11 UTC, akrabat commented on Slim/Middleware/BodyParsingMiddleware.php
> +            $body = (string)$request->getBody();
> What if the stream is not seekable (rewindable)?
> This would be a problem if any subsequent middleware, for whatever reason, needed to access the raw body.
> An example would be authentication via HMAC.

`__toString()` will rewind (if it can) and leaves the pointer back where it was before the call, so the stream won't look any different for subsequent middleware. (If it can't rewind, then nothing's changed of course.)


> One solution would be to simply copy the non-seekable stream to a new seekable stream.

If the stream is not rewindable, then there's no guarantee that the data at the beginning is anywhere in memory now, so I don't see any advantage to copying to seekable stream?

At the end of the day,  I think that if you're using a non-rewindable string in your ServerRequest, then you're incompatible with getParsedBody() and won't need or want this middleware.

2019-08-13 19:50 UTC, anfly0 commented on Slim/Middleware/BodyParsingMiddleware.php
> +            $body = (string)$request->getBody();
> 
> `__toString()` will rewind (if it can) and leaves the pointer back where it was before the call, so the stream won't look any different for subsequent middleware. (If it can't rewind, then nothing's changed of course.)

According to PSR-7 it is not a requirement to attempt to rewind the stream __after__ the data has been read by ` __to_string()`.  PSR-7 only requires the stream to be rewound __before__ the data is read. 
 
> If the stream is not rewindable, then there's no guarantee that the data at the beginning is anywhere in memory now, so I don't see any advantage to copying to seekable stream?
> 
> At the end of the day, I think that if you're using a non-rewindable string in your ServerRequest, then you're incompatible with getParsedBody() and won't need or want this middleware.

Well most often you will see something like `$streamFactory->createStreamFromFile('php://input')` when creating the body stream. 
The problem is that there is no guarantee `php://input` is seekable.
So the only real solution if the stream is not seekable and the raw data needs to access more than once is to copy the stream.

2019-08-13 20:06 UTC, akrabat commented on Slim/Middleware/BodyParsingMiddleware.php
> +            $body = (string)$request->getBody();
> Well most often you will see something like `$streamFactory->createStreamFromFile('php://input')` when creating the body stream.
> The problem is that there is no guarantee `php://input` is seekable.
> So the only real solution if the stream is not seekable and the raw data needs to access more than once is to copy the stream.

Right. I see what you're saying now. The problem is that we can't copy the stream as there's no method in `StreamInterface` that provide access to the underlying stream object.

Thoughts?

2019-08-13 20:13 UTC, akrabat commented on Slim/Middleware/BodyParsingMiddleware.php
> +            $body = (string)$request->getBody();
A further note. It looks like this has to be solved at the PSR-7 implementation level. e.g. Diactoros's [PhpInputStream](https://github.com/zendframework/zend-diactoros/blob/master/src/PhpInputStream.php).

2019-08-13 21:16 UTC, l0gicgate commented
@akrabat 

> $app->addBodyParsing();

I'd maybe rename that to `addBodyParsingMiddleware()`, I'd like to keep that suffix for all helper methods.

I mean theoretically we should probably do a helper for all internal middleware:
- ErrorMiddleware - Already Done
- RoutingMiddleware - Already Done
- BodyParsingMiddleware - We should add it
- ContentLengthMiddleware - We should add it
- MethodOverrideMiddleware - We should add it

What do you think @adriansuter

2019-08-13 21:22 UTC, l0gicgate commented on Slim/Middleware/BodyParsingMiddleware.php
> +            $body = (string)$request->getBody();
@akrabat this seems like such an oversight from the PSR-7 spec. It makes for unpredictable behavior. As discussed, we should leverage caching on `Slim-Psr7` to mitigate some of this unpredictability.

2019-08-13 21:47 UTC, anfly0 commented on Slim/Middleware/BodyParsingMiddleware.php
> +            $body = (string)$request->getBody();
@akrabat My thinking is that the simplest way to copy the stream would be something like:
```
$oldStream = $request->getBody();
while (!$oldStream->eof()) {
     $newStream->write($oldStream->read(4096));
}
$request = $request->withBody($newStream);
```
Maybe not the cleanest, but reasonably efficient.

2019-08-13 22:28 UTC, adriansuter commented
As long as there aren't dozens of internal middleware, why not. This would make things definitely more developer friendly.

But we need to pay attention not to blow up our `App` class.

Unfortunately this works only for internal middleware. So we would mix two "styles" of adding middleware. I'm not too happy with that, as I would prefer to make things consistent. But that is some sort of compromise, I guess.

2019-08-13 22:33 UTC, akrabat commented on Slim/Middleware/BodyParsingMiddleware.php
> +            $body = (string)$request->getBody();
> @akrabat My thinking is that the simplest way to copy the stream would be something like:
> 
> ```
> $oldStream = $request->getBody();
> while (!$oldStream->eof()) {
>      $newStream->write($oldStream->read(4096));
> }
> $request = $request->withBody($newStream);
> ```
> 
> Maybe not the cleanest, but reasonably efficient.

This doesn’t work because it closes the Stream object instance & not the underlying stream resource. Diactoros solves this with a special Stream class & I’ll see if I can do something for Slim’s Psr7 implementation.

2019-08-14 07:59 UTC, juliangut commented
> * ErrorMiddleware - Already Done
> 
> * RoutingMiddleware - Already Done
> 
> * BodyParsingMiddleware - We should add it
> 
> * ContentLengthMiddleware - We should add it
> 
> * MethodOverrideMiddleware - We should add it

Why not basic auth, cors, trailing slash, http cache or gzip/deflate encoding middlewares? I mean routing and error must of course be bundled with Slim but apart from those, there are already great PSR15 middleware out there for all those things

I was surprised yesterday when I saw this PR, I guess it is because you normally receive questions about how to support X payload, but that can be documented

Just my thoughts if they are of any use

2019-08-14 09:14 UTC, akrabat commented
> Why not basic auth, cors, trailing slash, http cache or gzip/deflate encoding middlewares? I mean routing and error must of course be bundled with Slim but apart from those, there are already great PSR15 middleware out there for all those things

The ones that @l0gicgate listed all functionality that was built into Slim 3. With Slim 4 we have moved them into separate components so that the user can now choose to replace with more appropriate solutions for their use-case. 

> I was surprised yesterday when I saw this PR, I guess it is because you normally receive questions about how to support X payload, but that can be documented

This one has come about because the solution we thought we had with Slim-Http does't work as well as we'd like with PSR-15, so this PR addresses that gap.

I don't think we're against supplying other middleware as optional components if we feel that it's something that Slim should come with out of the box and there's not a wide-used, simple-to-use option out there already.

2019-08-14 11:04 UTC, anfly0 commented on Slim/Middleware/BodyParsingMiddleware.php
> +            $body = (string)$request->getBody();
The only interesting thing about the underlying stream, in this case, is if it is seekable or not.
This can of course easily be checked with `$stream->isSeekable()`.
If it is not seekable, copy all the content to a new seekable stream (based on php//temp).
This approach would allow the PSR-7 implementation to use any resource when creating the request object.

My final thoughts is that:
As long as PSR-7 doesn't mandate that the stream is seekable, any middleware touching the stream will have to check if the stream is seekable and make sure that the stream is rewound before passing it to the handler.
In this way, the middleware is not coupled to any specific PSR-7 implementation.

2019-08-14 16:21 UTC, l0gicgate commented
> I would prefer to make things consistent

I'm hoping that this will be it for our internal middleware suite. I like consistency as well. So with that line of thinking I guess we should add helper methods for all of the internal middleware.

2019-08-14 16:22 UTC, l0gicgate commented on Slim/Middleware/BodyParsingMiddleware.php
> +            $body = (string)$request->getBody();
@anfly0 but what if the buffer is bigger than 4096 bytes? We need a better solution or just leave it as is.

2019-08-14 16:49 UTC, akrabat commented on Slim/Middleware/BodyParsingMiddleware.php
> +            $body = (string)$request->getBody();
> We need a better solution or just leave it as is.

My personal preference is to put caching into Slim-Psr7's Stream and turn it on for php://input. I have a proof of concept for this working locally and it seems to do what I expect.

2019-08-14 16:50 UTC, akrabat commented
> We can do that in a different PR though.

I've added App::addBodyParsingMiddleware() to this PR. I agree that separate PRs for the other middleware makes sense.

2019-08-14 16:52 UTC, shadowhand commented
I'm not sure if I am 👍 on this, because as @juliangut says, [middlewares/payload][1] already exists and works for any PSR-15 system.

[1]: https://packagist.org/packages/middlewares/payload

2019-08-14 17:01 UTC, shadowhand reviewed
As @juliangut says, [middlewares/payload][1] already exists and works for any PSR-15 system.

At minimum, I feel like this kind of solution would be better published as a separate package (or additional functionality contributed to `middlewares/payload`) that anyone can use with PSR-15 dispatchers. To me this largely feels like "not invented here" and, while pretty easy to use for simple applications, is not particularly flexible.

[1]: https://packagist.org/packages/middlewares/payload

2019-08-14 17:01 UTC, shadowhand commented on Slim/Middleware/BodyParsingMiddleware.php
> +    public function registerBodyParser(string $mediaType, callable $callable): self
Rather than a generic `callable`, why not create an interface?

```php
interface BodyParser
{
    public function canParse(string $contentType): bool;

    /**
     * @return mixed
     */
    public function parse(StreamInterface $stream);
}
```

Then you can do:

```php
$middleware = new BodyParsingMiddleware();
$middleware->register(new JsonParser());
$middleware->register(new XmlParser());
// etc
```

2019-08-14 17:01 UTC, shadowhand commented on Slim/Middleware/BodyParsingMiddleware.php
> +        $this->registerBodyParser('application/json', function ($input) {
This is fine for basic applications, but what about users of JSON-API that use `application/vnd.api+json` as the content type? The parsing is exactly the same but this hard lock on `application/json` won't work.

2019-08-14 17:01 UTC, shadowhand commented on Slim/Middleware/BodyParsingMiddleware.php
> +                $mediaType = 'application/' . $parts[count($parts) - 1];
Okay, I get that this is supposed to handle `application/vnd.api+json` using `application/json` parser... that behavior is not particularly obvious though, and would be better (IMO) handled on a case by case basis in a specific parser.

2019-08-14 17:32 UTC, l0gicgate commented on Slim/Middleware/BodyParsingMiddleware.php
> +    public function registerBodyParser(string $mediaType, callable $callable): self
I don't disagree with you on this. This to me feels like it should be extracted in its own package if we're going to go that route so we can contain the files contextually. The middleware we ship right now are self-contained into one file.

2019-08-14 17:48 UTC, anfly0 commented on Slim/Middleware/BodyParsingMiddleware.php
> +            $body = (string)$request->getBody();
@l0gicgate That what the while loop is for. It will copy 4096 bytes chunks until $oldStream->eof() is true. This is not a very uncommon way to copy stream-like objects.

2019-08-14 17:57 UTC, anfly0 commented on Slim/Middleware/BodyParsingMiddleware.php
> +            $body = (string)$request->getBody();
@akrabat Regardless of when and where the data gets copied, I think it's a good idea to only copy the data if the stream is not seekable. My _feeling_ is that copying the stream can be rather expensive and should be avoided if possible.

2019-08-14 19:49 UTC, l0gicgate commented on Slim/Middleware/BodyParsingMiddleware.php
> +            $body = (string)$request->getBody();
@anfly0 my bad I didn't see the while, oversight on my part.

2019-08-14 21:43 UTC, akrabat commented on Slim/Middleware/BodyParsingMiddleware.php
> +            $body = (string)$request->getBody();
> @akrabat Regardless of when and where the data gets copied, I think it's a good idea to only copy the data if the stream is not seekable. My _feeling_ is that copying the stream can be rather expensive and should be avoided if possible.

I’ll have a play & see what I can do.

2019-08-15 18:59 UTC, akrabat commented on Slim/Middleware/BodyParsingMiddleware.php
> +            $body = (string)$request->getBody();
@anfly0 I'm confused trying to do this.

If the stream is not seeable, then we can't rewind it and hence can't parse it in this middleware. Have I missed something?

2019-08-15 19:03 UTC, akrabat commented on Slim/Middleware/BodyParsingMiddleware.php
> +            $body = (string)$request->getBody();
So maybe I copy the stream if it's not seeable _and_ `$stream->tell()` is `0`?

2019-08-15 19:26 UTC, anfly0 commented on Slim/Middleware/BodyParsingMiddleware.php
> +            $body = (string)$request->getBody();
@akrabat I'm no 100 on this, but I think that `$stream->tell()` can return 0 on a not seekable stream even if some of the data has been read.
Offsets have no real meaning if the stream is not seekable.

One idea is to copy the stream if it's not seekable and then compare the size of the new stream with what's in the Content-Length header.
If the match it's reasonably safe to assume that all data was copied and if they don't some error handling can be done.

2019-08-15 19:30 UTC, akrabat commented on Slim/Middleware/BodyParsingMiddleware.php
> +            $body = (string)$request->getBody();
How do we get a non-seeable stream into a `ServerRequest`?

2019-08-15 19:37 UTC, l0gicgate approved these changes

2019-08-15 19:38 UTC, merged

2019-08-15 19:39 UTC, akrabat commented
@l0gicgate I'm happy with this as the first cut. The only potential outstanding issue is related to non-seekable streams and I'd like to see a real use-case for a non-seeable stream in a `ServerRequest` before try to solve it. The most common case is `php://input` which reports as seekable, but isn't really for PUT, so that needs to be handled at the PSR-7 implementation level..

2019-08-15 19:40 UTC, anfly0 commented on Slim/Middleware/BodyParsingMiddleware.php
> +            $body = (string)$request->getBody();
I'm not sure I understand the question.
The PSR-7 implementation used is free to use whatever resource or method to create the stream.
It is an edge case, but it is entirely possible for the stream not be seekable.

2019-08-21 17:18 UTC, esetnik commented
Are we supposed to use `$app->addBodyParsingMiddleware();` if we are also using `slim-http`? It seems this functionality is already included in `slim-http` so maybe it can be removed now that it's available in slim itself? See https://github.com/slimphp/Slim-Http/issues/99

2019-08-21 17:21 UTC, l0gicgate commented
@esetnik no need to use it no. And we are not removing it as you may use Slim-Http without using Slim

2019-08-21 17:40 UTC, akrabat commented
It is beneficial to have it in Slim-Http to help migration from Slim 3.