Optionally handle subclasses of exceptions in custom error handler
slimphp/Slim pull request #2862
Opened 2019-10-08 12:34 UTC by nickdnk

Hello guys

I thought this could be a nice addition, so a particular app can decide to handle all subclasses of an exception with one handler. This is nice way to keep things separated.

I added this as an option that defaults to false so this *should* not be a breaking change, but I'm not 100% sure.

What do you think?

2019-10-08 12:39 UTC, nickdnk commented
Force pushed for typo.

2019-10-08 13:01 UTC, nickdnk commented
We could mitigate the BC by doing this instead:

```
if (isset($this->handlers[$type])) {
    return $this->callableResolver->resolve(
        is_array($this->handlers[$type]) ? $this->handlers[$type]['handler'] : $this->handlers[$type]
    );
} else {
    foreach ($this->handlers as $class => $handler) {
        if (is_array($handler) && $handler['handle_subclass'] === true) {
            if (is_subclass_of($type, $class)) {
                return $this->callableResolver->resolve($handler['handler']);
            }
        }
    }
}
```

Then even if a someone has subclassed ErrorMiddleware *and* overriden $handlers to contain callables, it wouldn't break.

2019-10-12 15:36 UTC, l0gicgate commented
@adriansuter I think this would be a good addition and there's no BC breaks. What do you think about it?

2019-10-12 17:18 UTC, nickdnk commented
Is there a reason that `$handlers` is `protected` and not `private` ? Given how close this variable is tied to the `setErrorHandler` method, should it be visible to a subclass?

2019-11-08 17:35 UTC, l0gicgate commented
> Is there a reason that $handlers is protected and not private ? Given how close this variable is tied to the setErrorHandler method, should it be visible to a subclass?

In case one wants to extend `ErrorMiddleware` we left it as protected.

2019-11-08 22:19 UTC, adriansuter reviewed
That is a good idea.

Another solution would be to add a new protected property `subClassHandlers` and then just write 
```php
    public function setErrorHandler(string $type, $handler, bool $handleSubclasses = false): self
    {
        if ($handleSubclasses) {
            $this->subClassHandlers[$type] = $handler;
        } else {
            $this->handlers[$type] = $handler;
        }

        return $this;
    }
```

That way, we do not change the data logic of the `handlers` property which is expected to be a plain array of handlers.

Of course we would have to change `getErrorHandler()` too.
```php
    public function getErrorHandler(string $type)
    {
        if (isset($this->handlers[$type])) {
            return $this->callableResolver->resolve($this->handlers[$type]);
        } elseif (isset($this->subClassHandlers[$type])) {
            return $this->callableResolver->resolve($this->subClassHandlers[$type]);
        } else {
            foreach ($this->subClassHandlers as $class => $handler) {
                if (is_subclass_of($type, $class)) {
                    return $this->callableResolver->resolve($handler);
                }
            }
        }

        return $this->getDefaultErrorHandler();
    }
```

That way, we would also get rid of the double `if`-statements in the `foreach` loop.

What do you mean, @l0gicgate and @nickdnk ? If you want to leave it as requested in this PR, then I am fine too.

2019-11-08 22:22 UTC, nickdnk commented
I think yours is a good workaround, @adriansuter.

2019-11-18 20:15 UTC, l0gicgate commented
@adriansuter I like your solution. We should proceed with that.

2019-11-19 23:19 UTC, nickdnk commented
Updated the PR.

Also, I added phpdocs for the handler arrays based on the value of `$defaultErrorHandler` - but I'm not entirely sure that you can annotate them as `ErrorHandlerInterface` since they're functions?

2019-11-20 19:32 UTC, l0gicgate commented
Need to write tests as well for the subclass case. Are you able to do that?

2019-11-20 19:55 UTC, nickdnk commented
I did. I don't know why it claims it wasn't covered. There is a test for both with and without subclass use.

2019-11-20 21:20 UTC, adriansuter commented
Did you add a test case for the case you set an error handler as subclass handler, but the exception thrown is not a subclass but exactly that class?

`} elseif (isset($this->subClassHandlers[$type])) {`

2019-11-20 21:46 UTC, nickdnk commented
I think that did it.

2019-11-27 18:15 UTC, l0gicgate requested changes

2019-11-27 18:15 UTC, l0gicgate commented on tests/Middleware/ErrorMiddlewareTest.php
> +
Can you remove this blank line please.

2019-11-27 18:15 UTC, l0gicgate commented on tests/Middleware/ErrorMiddlewareTest.php
> +
Can you remove this blank line please.

2019-12-10 03:16 UTC, l0gicgate approved these changes

2019-12-10 03:16 UTC, merged