Change route context attribute names
slimphp/Slim pull request #2889
Opened 2019-11-28 23:23 UTC by adriansuter

PR for #2883 

The attribute names are even configurable - although I am not sure if that should be an option. If not, let me know - I will remove all the unnecessary calls to static methods and instead hard code the attribute names.

If yes, maybe we could find another solution than using static methods and properties in the `RouteContext` class - I am not totally happy with this *static* solution.

2019-11-29 07:41 UTC, adriansuter commented
# Proposition

Pass an optional `RouteContextFactoryInterface` to the App. In `App::handle()` use that factory to create a route context and attach it to the request.

So we need
```php
RouteContextFactoryInterface::createRouteContext():RouteContextInterface;
RouteContext::attach(ServerRequestInterface, RouteContextInterface):ServerRequestInterface;
```

Then, whenever we need that route context, we can grab it from the `$request`.

```php
RouteContext::fromRequest(ServerRequestInterface):RouteContextInterface
```

The `RouteContextInterface` has methods to set and get route parser, routing results, base path and route.

Warning: A lot of phpunit test cases would need rewrites.

2019-11-29 16:58 UTC, l0gicgate commented on Slim/Routing/RouteContext.php
> +    public static function setRouteAttributeName(string $routeAttributeName): void
I don't think these setters are necessary since it's for internal purposes.

2019-11-29 16:59 UTC, l0gicgate commented on Slim/Routing/RouteContext.php
> +    private static $routeAttributeName = '__route__';
We should make these public constants so we can use them in our test cases, makes it easier to refactor if needed.

2019-11-29 17:00 UTC, l0gicgate commented on tests/Middleware/RoutingMiddlewareTest.php
> +            $route = $request->getAttribute('__route__');
as mentioned above, we should use public constants on the `RouteContext` object.

2019-11-29 17:01 UTC, l0gicgate commented on Slim/Routing/RouteContext.php
> +    public static function attachRoute(ServerRequestInterface $request, RouteInterface $route): ServerRequestInterface
If we use constants we can get rid of all the `attachX` methods also

2019-11-29 17:50 UTC, l0gicgate requested changes
Let's remove the `_ATTRIBUTE_NAME` suffix from the constants, then it's good to go!

2019-11-29 18:08 UTC, adriansuter commented
Good to go.

2019-11-29 18:09 UTC, l0gicgate approved these changes

2019-11-29 18:10 UTC, merged

2019-11-30 04:29 UTC, jacekkarczmarczyk commented
I'm not familar with v4 yet so I wasn't sure if this attribute names where a public this, but apparently they are, so changing them is definitely a breaking change. 

I'd rather see these names as configurable thing (with default names unchanged, `'route'` etc) in `RouteContextConfig` or something like this, which could be injected to classes that use the attributes. Probably  there could be also `RouteContextFactory` that would have `RouteContextConfig` injected in the constructor, otherwise you should pass the config in `RouteContext::fromRequest` arguments

That would be then a feature/minor release of course

2019-11-30 20:27 UTC, N1ghteyes commented
can  confirm that this is a breaking change as per my issue - referencing the docs is one thing (my original code came from v4 docs - one of the basic examples i think) but if possible i would like to see Slim avoid breaking changes in minor releases.

2019-11-30 22:58 UTC, l0gicgate commented
> can confirm that this is a breaking change as per my issue

Your issue is unrelated to this. As I mentioned, pattern matching is done via FastRoute, which isn't code that was touched by this PR. 

> i would like to see Slim avoid breaking changes in minor releases.

We do too however using the request attributes directly isn't the correct way to access the route/routing results/base path/etc. While it was originally stated that way in the earlier version of the v4 docs, this was a mistake and has since been changed. Using the `RouteContext` object which was in the original 4.0.0 release would have avoided any potential breaks.