Render errors uniformly
slimphp/Slim pull request #2896
Opened 2019-12-12 15:40 UTC by adbrvn

In this PR solved several problems 

* Render error uniformly in different formats (#2746)
* Render http exceptions as custom error pages
* Hide backtraces in plain format too

2019-12-17 20:00 UTC, l0gicgate commented
This is great, thank you for this contribution.

2019-12-18 15:23 UTC, adriansuter requested changes
Great, thanks. Only two minor issues.

2019-12-18 15:23 UTC, adriansuter commented on tests/Error/AbstractErrorRendererTest.php
> +use Psr\Http\Message\ServerRequestInterface;
The `ServerRequestInterface` could be removed.

2019-12-18 15:23 UTC, adriansuter commented on tests/Error/AbstractErrorRendererTest.php
> +use function json_decode;
This `use function json_decode;` can be removed, as Slim is not using root namespaced php function calls.

2019-12-18 20:14 UTC, l0gicgate commented on Slim/Error/AbstractErrorRenderer.php
> +        return 'Slim Application Error';
We should actually make this a protected variable so it can be overridden without having to override the entire method

2019-12-20 15:34 UTC, adbrvn commented on tests/Error/AbstractErrorRendererTest.php
> +use Psr\Http\Message\ServerRequestInterface;
fixed

2019-12-20 15:34 UTC, adbrvn commented on tests/Error/AbstractErrorRendererTest.php
> +use function json_decode;
fixed

2019-12-20 15:35 UTC, adbrvn commented on Slim/Error/AbstractErrorRenderer.php
> +        return 'Slim Application Error';
fixed

2019-12-20 17:32 UTC, adriansuter commented
Travis fails because of `prophecy` - see https://github.com/slimphp/Slim/issues/2901

2019-12-20 21:17 UTC, l0gicgate commented on Slim/Error/AbstractErrorRenderer.php
> +
remove this extra white line please

2019-12-20 21:18 UTC, l0gicgate commented
This PR is good to go. We just need to wait for #2901 to merge

2019-12-20 21:19 UTC, adriansuter approved these changes

2019-12-20 21:28 UTC, l0gicgate commented
@adriansuter we could prophesize the tests also instead of using mockbuilder for uniformity. We have time since we have to wait anyway. What do you think? I or you can do it since he probably doesn't know how to

2019-12-20 21:35 UTC, adriansuter commented
@l0gicgate Why not, uniformity is always a good thing. I think we will have plenty of time indeed - and then there is also Christmas and New Year coming. Feel free to prophesize the mocks.

2019-12-21 16:55 UTC, adbrvn commented on Slim/Error/AbstractErrorRenderer.php
> +
fixed

2019-12-22 00:08 UTC, l0gicgate commented
I'm locking Prophecy version to 1.9 and merging this. We will address issue in #2901. Won't release 4.4.0 until that's resolved.

2019-12-22 00:08 UTC, merged