Array routes
slimphp/Slim pull request #3069
Opened 2021-04-17 15:38 UTC by ddrv

These changes will allow the route handler to be specified as an array. This allows you to open the handler method in PhPStorm in ctrl + click, and also allows you to avoid the "unused method" type of bindings. 

For example:

```php
<?php

$app->get('/', [App\Controllers\PageController::class, 'home'])->setName('home');
```

2021-04-18 05:18 UTC, l0gicgate requested changes
Great work, I like this. We're going to have to add documentation for this as well.

2021-04-18 05:18 UTC, l0gicgate commented on Slim/CallableResolver.php
> +        $array = $toResolve;
can we rename this variable to `$candidate` please and add a blank line after the `if` statement

2021-04-18 05:18 UTC, l0gicgate commented on tests/CallableResolverTest.php
> +        $this->expectExceptionMessage('Callable Unknown does not exist');
I think that we could make these error messages more relevant. We should include the method as well in the message if it exists. Right now we only show the class name.

2021-04-18 09:08 UTC, ddrv commented
> We're going to have to add documentation for this as well.

- [x] [Pull Request](https://github.com/slimphp/Slim-Website/pull/560)

2021-04-19 17:18 UTC, l0gicgate approved these changes

2021-04-19 17:19 UTC, merged

2021-04-19 17:19 UTC, l0gicgate commented
@ddrv great work, thank you for your contribution