Is null
slimphp/Slim pull request #3214
Opened 2022-07-04 16:18 UTC by MathiasReker

Replaces is_null($var) expression with null === $var.

2022-07-06 14:08 UTC, l0gicgate requested changes

2022-07-06 14:08 UTC, l0gicgate commented on Slim/Middleware/BodyParsingMiddleware.php
> +            if (null !== $parsed && !is_object($parsed) && !is_array($parsed)) {
No yoda conditions. Let's do `$parsed !== null` instead

2022-07-07 12:11 UTC, MathiasReker commented on Slim/Middleware/BodyParsingMiddleware.php
> +            if (null !== $parsed && !is_object($parsed) && !is_array($parsed)) {
```suggestion
            if ($parsed !== null && !is_object($parsed) && !is_array($parsed)) {
```

2022-07-07 12:13 UTC, nbayramberdiyev approved these changes

2022-07-07 17:21 UTC, l0gicgate approved these changes

2022-07-07 17:21 UTC, merged