replace string functions with multi byte forms
slimphp/Slim pull request #3217
Opened 2022-07-06 11:25 UTC by mehdihasanpour

2022-07-06 15:58 UTC, nbayramberdiyev commented
This branch is outdated.

2022-07-07 15:07 UTC, mehdihasanpour commented
> This branch is outdated.

It is updated right now.

2022-07-08 10:16 UTC, nbayramberdiyev requested changes

2022-07-08 10:16 UTC, nbayramberdiyev commented on Slim/App.php
> +        $method = mb_strtoupper($request->getMethod());
Do we really need this since we're not operating on a Unicode string?

2022-07-08 10:16 UTC, nbayramberdiyev commented on Slim/Middleware/BodyParsingMiddleware.php
> +            return mb_strtolower(trim($contentTypeParts[0]));
Same here.

2022-07-08 10:16 UTC, nbayramberdiyev commented on Slim/Middleware/MethodOverrideMiddleware.php
> +        } elseif (mb_strtoupper($request->getMethod()) === 'POST') {
Same here.

2022-07-08 10:16 UTC, nbayramberdiyev commented on Slim/ResponseEmitter.php
> +            $first = mb_strtolower($name) !== 'set-cookie';
Same here.

2022-07-08 10:16 UTC, nbayramberdiyev commented on tests/AppTest.php
> +        $methodName = mb_strtolower($method);
Same here.

2022-07-08 12:09 UTC, closed without merging