Refactor some code
slimphp/Slim pull request #3218
Opened 2022-07-06 11:44 UTC by mehdihasanpour

2022-07-06 15:55 UTC, nbayramberdiyev requested changes

2022-07-06 15:55 UTC, nbayramberdiyev commented on tests/bootstrap.php
> +            return ! (stripos($file, 'non-readable.cache') !== false)
You can simply do this:
```php
return stripos($file, 'non-readable.cache') === false;
```

2022-07-06 15:55 UTC, nbayramberdiyev commented on tests/bootstrap.php
> +            return ! (stripos($path, 'non-writable-directory') !== false)
Same as above.

2022-07-06 17:23 UTC, mehdihasanpour commented on tests/bootstrap.php
> +            return ! (stripos($file, 'non-readable.cache') !== false)
Thanks, this is a better way.

2022-07-07 12:18 UTC, nbayramberdiyev commented on tests/bootstrap.php
> +            return ! (stripos($file, 'non-readable.cache') !== false)
Can you also unwrap the code parentheses?

2022-07-07 12:26 UTC, mehdihasanpour commented on tests/bootstrap.php
> +            return ! (stripos($file, 'non-readable.cache') !== false)
I unwrapped the code parentheses.

2022-07-07 12:30 UTC, nbayramberdiyev approved these changes

2022-07-07 17:32 UTC, l0gicgate approved these changes

2022-07-07 17:38 UTC, merged