Refactor
slimphp/Slim pull request #3220
Opened 2022-07-10 17:59 UTC by amirkhodabande

2022-11-05 20:04 UTC, akrabat commented on tests/Handlers/Strategies/RequestResponseNamedArgsTest.php
> +    private const LAST_PHP_VERSION_ID = 80000;
Please name as `PHP_8_0_VERSION_ID`

2022-11-05 20:05 UTC, akrabat requested changes
In addition to the constant name, please rebase against 4.x and fix conflicts.

2022-11-06 17:30 UTC, amirkhodabande commented
> In addition to the constant name, please rebase against 4.x and fix conflicts.

2022-11-07 21:33 UTC, akrabat approved these changes
LGTM. Thanks.

2022-11-07 21:33 UTC, merged