Typos fixes.
slimphp/Slim pull request #3232
Opened 2022-10-03 20:55 UTC by jpmbandolin

Some PHPDocs where completed to include thrown exceptions.
Some PHPDocs typos where fixed.

2022-10-04 12:58 UTC, theodorejb requested changes

2022-10-04 12:58 UTC, theodorejb commented on Slim/CallableResolver.php
> +     * @param string          $defaultMethod
Why duplicate type information that is already in the function signature?

2022-10-04 12:58 UTC, theodorejb commented on Slim/App.php
> +     * @return App
Why duplicate the return type info?

2022-10-04 12:58 UTC, theodorejb commented on Slim/CallableResolver.php
> +     * @throws ContainerExceptionInterface
What is the point of duplicating the return type info and adding these `@throws` annotations?

2022-10-04 12:58 UTC, theodorejb commented on Slim/CallableResolver.php
> -     * @throws RuntimeException
This method does throw a `RuntimeException`. Why replace this annotation?

Also, the parameter type shouldn't be duplicated.

2022-10-04 12:58 UTC, theodorejb commented on Slim/Factory/AppFactory.php
> +     * @throws ContainerExceptionInterface
Why add `@throws` annotations which the method itself doesn't throw?

Also, the parameter and return type shouldn't be duplicated.

2022-10-04 12:58 UTC, theodorejb commented on Slim/Middleware/OutputBufferingMiddleware.php
> +            throw new InvalidArgumentException("Invalid style `$style`. Must be `append` or `prepend`");
Why change this?

2022-10-04 14:09 UTC, l0gicgate commented
We've removed some of the docblocs because of return types they are not needed anymore and can be inferred by IDEs. 

Can we focus on only fixing typos on this PR?

2022-11-05 20:00 UTC, akrabat commented
Closing as no response from creator. Feel free to reopen when addressed.

2022-11-05 20:00 UTC, closed without merging