Persist routes indexed by name in RouteCollector for improved performance.
slimphp/Slim pull request #3235
Opened 2022-11-05 16:27 UTC by BusterNeece

In our application, we have what I think is a reasonable number of routes defined (a few dozen), and we're often calling `RouteParserInterface::relativeUrlFor` and its related functions. Under the hood, these all call `RouteCollectorInterface::getNamedRoute`, and right now, that's iterating through _every_ single route, checking the name, and returning the result if it finds it.

Individually, these calls aren't a big deal, but they add up fast. If, say, you're returning an API response with several records with several links in each row, this tends to result in a _huge_ number of calls to `RouteInterface::getName()`.

As a result of their exposed methods, the nature of the `RouteCollectorInterface` and `RouteParserInterface` means that it isn't possible to implement a lookup table like this in one's own code without reimplementing the entire `RouteParserInterface::relativeUrlFor` functionality.

However, fortunately that also means that this change can be made at the Slim level without any change to the interface. The logic here is identical to how it functions currently (the first route with a given name is returned by `getNamedRoute()`).

2022-11-05 20:14 UTC, akrabat requested changes
Thanks for this! Just a few changes that would be useful.

2022-11-05 20:14 UTC, akrabat commented on Slim/Routing/RouteCollector.php
> +
I'm pretty sure that a name can be assigned to a route after adding to the route collector, so can we keep the iteration if the lookup fails please? If the iteration finds a route that is not in `routesByName`, then add it for the next lookup.

2022-11-05 20:14 UTC, akrabat commented on Slim/Routing/RouteCollector.php
> +            return $this->routesByName[$name];
I think that it's possible that route has been renamed since it was mapped. Can we check the current name of the route in `routesByName[$name]` and if it's not the same as `$name`, remove it from `routesByName` and then fall through to the iteration search?

2022-11-05 20:14 UTC, akrabat commented on Slim/Routing/RouteCollector.php
> +        if (null !== $routeName && !isset($this->routesByName[$routeName])) {
`s/null !== $routeName/$routeName !== null/` as we don't do Yoda conditions here.

2022-11-05 20:45 UTC, BusterNeece commented
@akrabat Changes should be incorporated now.

2022-11-06 16:33 UTC, akrabat approved these changes

2022-11-06 16:33 UTC, merged

2022-11-06 16:33 UTC, akrabat commented
Thanks